//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acciones
    {
        public Acciones()
        {
            this.Rol_Acciones = new HashSet<Rol_Acciones>();
        }
    
        public int id_accion { get; set; }
        public string nombre { get; set; }
        public int id_controlador { get; set; }
    
        public virtual Controladores Controladores { get; set; }
        public virtual ICollection<Rol_Acciones> Rol_Acciones { get; set; }
    }
}
