//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acciones
    {
        public Acciones()
        {
            this.Rol_Acciones = new HashSet<Rol_Acciones>();
        }
    
        public int id_accion { get; set; }
        public string nombre { get; set; }
        public int id_controlador { get; set; }
    
        public virtual Controladores Controladores { get; set; }
        public virtual ICollection<Rol_Acciones> Rol_Acciones { get; set; }
    }
}
