//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicaciones
    {
        public Aplicaciones()
        {
            this.Controladores = new HashSet<Controladores>();
            this.Roles = new HashSet<Roles>();
        }
    
        public int id_aplicacion { get; set; }
        public string nombre { get; set; }
        public string ruta { get; set; }
    
        public virtual ICollection<Controladores> Controladores { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
