//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicaciones
    {
        public Aplicaciones()
        {
            this.Controladores = new HashSet<Controladores>();
            this.Roles = new HashSet<Roles>();
        }
    
        public int id_aplicacion { get; set; }
        public string nombre { get; set; }
        public string ruta { get; set; }
    
        public virtual ICollection<Controladores> Controladores { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
