//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public Archivo()
        {
            this.Archivo_Empleado = new HashSet<Archivo_Empleado>();
            this.Curso_Empleado = new HashSet<Curso_Empleado>();
        }
    
        public int id_archivo { get; set; }
        public int id_tipo_archivo { get; set; }
        public string nombre { get; set; }
        public string ubicacion { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
    
        public virtual Tipo_Archivo Tipo_Archivo { get; set; }
        public virtual ICollection<Archivo_Empleado> Archivo_Empleado { get; set; }
        public virtual ICollection<Curso_Empleado> Curso_Empleado { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
