//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public Articulos()
        {
            this.Egreso_Detalle = new HashSet<Egreso_Detalle>();
            this.Ingreso_Detalle = new HashSet<Ingreso_Detalle>();
            this.Transaccion_Inventario_Detalle = new HashSet<Transaccion_Inventario_Detalle>();
            this.Traslado_Detalle = new HashSet<Traslado_Detalle>();
        }
    
        public int id_articulo { get; set; }
        public int id_articulo_tipo { get; set; }
        public int serie { get; set; }
        public int id_marca { get; set; }
        public int id_proveedor { get; set; }
        public decimal costo { get; set; }
        public decimal costo_venta { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_bodega { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Articulo_Tipo Articulo_Tipo { get; set; }
        public virtual Bodegas Bodegas { get; set; }
        public virtual Marcas Marcas { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual ICollection<Egreso_Detalle> Egreso_Detalle { get; set; }
        public virtual ICollection<Ingreso_Detalle> Ingreso_Detalle { get; set; }
        public virtual ICollection<Transaccion_Inventario_Detalle> Transaccion_Inventario_Detalle { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
        public virtual ICollection<Traslado_Detalle> Traslado_Detalle { get; set; }
    }
}
