//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bodegas
    {
        public Bodegas()
        {
            this.Articulos = new HashSet<Articulos>();
            this.Bodega_Inventario_Consumibles = new HashSet<Bodega_Inventario_Consumibles>();
            this.Bodega_Inventario_Municiones = new HashSet<Bodega_Inventario_Municiones>();
            this.Bodega_Inventario_Uniformes = new HashSet<Bodega_Inventario_Uniformes>();
            this.Transaccion_Inventario_Detalle = new HashSet<Transaccion_Inventario_Detalle>();
            this.Armas = new HashSet<Armas>();
            this.Egresos = new HashSet<Egresos>();
            this.Egresos1 = new HashSet<Egresos>();
            this.Ingresos = new HashSet<Ingresos>();
            this.Traslados = new HashSet<Traslados>();
            this.Traslados1 = new HashSet<Traslados>();
        }
    
        public int id_bodega { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
    
        public virtual ICollection<Articulos> Articulos { get; set; }
        public virtual ICollection<Bodega_Inventario_Consumibles> Bodega_Inventario_Consumibles { get; set; }
        public virtual ICollection<Bodega_Inventario_Municiones> Bodega_Inventario_Municiones { get; set; }
        public virtual ICollection<Bodega_Inventario_Uniformes> Bodega_Inventario_Uniformes { get; set; }
        public virtual ICollection<Transaccion_Inventario_Detalle> Transaccion_Inventario_Detalle { get; set; }
        public virtual ICollection<Armas> Armas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
        public virtual ICollection<Egresos> Egresos { get; set; }
        public virtual ICollection<Egresos> Egresos1 { get; set; }
        public virtual ICollection<Ingresos> Ingresos { get; set; }
        public virtual ICollection<Traslados> Traslados { get; set; }
        public virtual ICollection<Traslados> Traslados1 { get; set; }
    }
}
