//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carga_Estado_Fuerza_Detalle
    {
        public int id_carga_estado_fuerza_detalle { get; set; }
        public string id_empleado { get; set; }
        public int id_carga_estado_fuerza { get; set; }
        public string id_cat_tipo_agente { get; set; }
        public string id_ubicacion { get; set; }
        public string id_situacion { get; set; }
        public string observacion { get; set; }
    
        public virtual Carga_Estado_Fuerza Carga_Estado_Fuerza { get; set; }
    }
}
