//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carga_Estado_Fuerza
    {
        public Carga_Estado_Fuerza()
        {
            this.Carga_Estado_Fuerza_Detalle = new HashSet<Carga_Estado_Fuerza_Detalle>();
        }
    
        public int id_carga_estado_fuerza { get; set; }
        public int id_estado_fuerza { get; set; }
        public string nombre_archivo { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_usuario_creacion { get; set; }
    
        public virtual ICollection<Carga_Estado_Fuerza_Detalle> Carga_Estado_Fuerza_Detalle { get; set; }
        public virtual Estado_Fuerza Estado_Fuerza { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
