//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carga_Estado_Fuerza_Detalle
    {
        public int id_carga_estado_fuerza_detalle { get; set; }
        public string id_empleado { get; set; }
        public int id_carga_estado_fuerza { get; set; }
        public string id_cat_tipo_agente { get; set; }
        public string id_ubicacion { get; set; }
        public string id_situacion { get; set; }
        public string observacion { get; set; }
    
        public virtual Carga_Estado_Fuerza Carga_Estado_Fuerza { get; set; }
    }
}
