//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carga_Estado_Fuerza
    {
        public Carga_Estado_Fuerza()
        {
            this.Carga_Estado_Fuerza_Detalle = new HashSet<Carga_Estado_Fuerza_Detalle>();
        }
    
        public int id_carga_estado_fuerza { get; set; }
        public int id_estado_fuerza { get; set; }
        public string nombre_archivo { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int id_usuario_creacion { get; set; }
    
        public virtual ICollection<Carga_Estado_Fuerza_Detalle> Carga_Estado_Fuerza_Detalle { get; set; }
        public virtual Estado_Fuerza Estado_Fuerza { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
