//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratacion
    {
        public Contratacion()
        {
            this.Vacacion_Contrato = new HashSet<Vacacion_Contrato>();
            this.Vacacion_Contrato1 = new HashSet<Vacacion_Contrato>();
            this.Empleado_Encabezado_Planilla = new HashSet<Empleado_Encabezado_Planilla>();
            this.Empleado_Encabezado_Planilla1 = new HashSet<Empleado_Encabezado_Planilla>();
        }
    
        public int id_contratacion { get; set; }
        public int id_empresa { get; set; }
        public int id_puesto { get; set; }
        public int id_empleado { get; set; }
        public int id_salario { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> id_estado_empleado { get; set; }
        public Nullable<int> id_ubicacion { get; set; }
        public Nullable<int> id_motivo_baja { get; set; }
        public string referido_por { get; set; }
        public string razon_baja { get; set; }
    
        public virtual Estado_Empleado Estado_Empleado { get; set; }
        public virtual ICollection<Vacacion_Contrato> Vacacion_Contrato { get; set; }
        public virtual ICollection<Vacacion_Contrato> Vacacion_Contrato1 { get; set; }
        public virtual Puesto Puesto { get; set; }
        public virtual Salario Salario { get; set; }
        public virtual ICollection<Empleado_Encabezado_Planilla> Empleado_Encabezado_Planilla { get; set; }
        public virtual ICollection<Empleado_Encabezado_Planilla> Empleado_Encabezado_Planilla1 { get; set; }
        public virtual Motivo_Baja Motivo_Baja { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
