//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratos_Otros_Servicios
    {
        public Contratos_Otros_Servicios()
        {
            this.Facturas_Detalle = new HashSet<Facturas_Detalle>();
            this.Procesos_Facturacion_Detalle = new HashSet<Procesos_Facturacion_Detalle>();
        }
    
        public int id_contrato_otro_servicio { get; set; }
        public int id_contrato_servicio { get; set; }
        public int id_razon_social { get; set; }
        public Nullable<int> id_ubicacion { get; set; }
        public Nullable<int> id_razon_social_grupo_factura { get; set; }
        public int id_cat_otro_servicio { get; set; }
        public int cantidad { get; set; }
        public decimal costo { get; set; }
        public decimal precio_venta_unitario { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public string descripcion_eliminacion { get; set; }
    
        public virtual Razones_Sociales Razones_Sociales { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
        public virtual Cat_Otros_Servicios Cat_Otros_Servicios { get; set; }
        public virtual Contratos_Servicios Contratos_Servicios { get; set; }
        public virtual ICollection<Facturas_Detalle> Facturas_Detalle { get; set; }
        public virtual Razon_Social_Grupos_Factura Razon_Social_Grupos_Factura { get; set; }
        public virtual ICollection<Procesos_Facturacion_Detalle> Procesos_Facturacion_Detalle { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
