//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso_Empleado
    {
        public int id_curso_empleado { get; set; }
        public int id_capacitacion_impartida { get; set; }
        public int id_empleado { get; set; }
        public int id_instructor { get; set; }
        public int id_curso { get; set; }
        public Nullable<bool> extra { get; set; }
        public Nullable<int> nota { get; set; }
        public Nullable<bool> aprobado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public Nullable<int> id_archivo { get; set; }
    
        public virtual Capacitacion_Impartida Capacitacion_Impartida { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Archivo Archivo { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
