//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Empresa_Notorio = new HashSet<Empresa_Notorio>();
            this.Encabezado_Planilla = new HashSet<Encabezado_Planilla>();
            this.Representante_Empresa = new HashSet<Representante_Empresa>();
            this.Contratacion = new HashSet<Contratacion>();
            this.Tipo_Puesto = new HashSet<Tipo_Puesto>();
        }
    
        public int id_empresa { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public int telefono { get; set; }
        public string correo { get; set; }
        public int id_pais { get; set; }
        public bool prestaciones { get; set; }
        public string encabezado_boleta { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public string centro_trabajo { get; set; }
        public Nullable<int> zona { get; set; }
        public Nullable<int> fax { get; set; }
        public string contacto { get; set; }
        public Nullable<int> id_municipio { get; set; }
        public Nullable<int> nit { get; set; }
        public Nullable<int> numero_patronal { get; set; }
        public string nombre_comercial { get; set; }
    
        public virtual Municipios Municipios { get; set; }
        public virtual ICollection<Empresa_Notorio> Empresa_Notorio { get; set; }
        public virtual ICollection<Encabezado_Planilla> Encabezado_Planilla { get; set; }
        public virtual ICollection<Representante_Empresa> Representante_Empresa { get; set; }
        public virtual ICollection<Contratacion> Contratacion { get; set; }
        public virtual Paises Paises { get; set; }
        public virtual ICollection<Tipo_Puesto> Tipo_Puesto { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
