//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado_Fuerza_Detalle
    {
        public int id_estado_fuerza_detalle { get; set; }
        public int id_estado_fuerza { get; set; }
        public int id_empleado { get; set; }
        public int id_ubicacion { get; set; }
        public int id_situacion { get; set; }
        public int id_cat_tipo_agente { get; set; }
        public string observacion { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Estado_Fuerza Estado_Fuerza { get; set; }
        public virtual Situacion Situacion { get; set; }
        public virtual Cat_Tipos_Agente Cat_Tipos_Agente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
