//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado_Fuerza
    {
        public Estado_Fuerza()
        {
            this.Carga_Estado_Fuerza = new HashSet<Carga_Estado_Fuerza>();
            this.Estado_Fuerza_Detalle = new HashSet<Estado_Fuerza_Detalle>();
        }
    
        public int id_estado_fuerza { get; set; }
        public System.DateTime fecha { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public Nullable<System.DateTime> fecha_finalizacion { get; set; }
        public Nullable<int> id_usuario_finalizacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
    
        public virtual ICollection<Carga_Estado_Fuerza> Carga_Estado_Fuerza { get; set; }
        public virtual ICollection<Estado_Fuerza_Detalle> Estado_Fuerza_Detalle { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
        public virtual Usuarios Usuarios3 { get; set; }
    }
}
