//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public Facturas()
        {
            this.Facturas_Detalle = new HashSet<Facturas_Detalle>();
        }
    
        public int id_factura { get; set; }
        public int id_serie_factura { get; set; }
        public string serie { get; set; }
        public int numero_factura { get; set; }
        public int id_razon_social { get; set; }
        public string nombre_factura { get; set; }
        public string nit { get; set; }
        public string direccion { get; set; }
        public System.DateTime fecha_factura { get; set; }
        public string descripcion { get; set; }
        public decimal total { get; set; }
        public int id_cat_estado_factura { get; set; }
        public Nullable<System.DateTime> fecha_cobro { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<int> id_cat_razon_anulacion { get; set; }
        public string comentario_anulacion { get; set; }
        public Nullable<int> id_cat_razon_eliminacion { get; set; }
        public string comentario_eliminacion { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public Nullable<int> orden_aceptacion_numero { get; set; }
    
        public virtual Razones_Sociales Razones_Sociales { get; set; }
        public virtual Cat_Estados_Factura Cat_Estados_Factura { get; set; }
        public virtual Cat_Razones_Anulacion Cat_Razones_Anulacion { get; set; }
        public virtual Cat_Razones_Eliminacion Cat_Razones_Eliminacion { get; set; }
        public virtual Series_Facturas Series_Facturas { get; set; }
        public virtual ICollection<Facturas_Detalle> Facturas_Detalle { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
