//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestion_Cobro_Detalle
    {
        public Gestion_Cobro_Detalle()
        {
            this.Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle = new HashSet<Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle>();
        }
    
        public int id_gestion_cobro_detalle { get; set; }
        public int id_gestion_cobro { get; set; }
        public Nullable<System.DateTime> fecha_realizado { get; set; }
        public Nullable<int> id_cat_tipo_gestion_realizada { get; set; }
        public System.DateTime fecha_proyectada { get; set; }
        public int id_cat_tipo_gestion_proyectada { get; set; }
        public Nullable<int> id_cat_tipo_respuesta_gestion { get; set; }
        public bool realizada { get; set; }
        public string comentario { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
    
        public virtual Cat_Tipos_Gestion Cat_Tipos_Gestion { get; set; }
        public virtual Cat_Tipos_Gestion Cat_Tipos_Gestion1 { get; set; }
        public virtual Cat_Tipos_Respuesta_Gestion Cat_Tipos_Respuesta_Gestion { get; set; }
        public virtual Gestion_Cobro Gestion_Cobro { get; set; }
        public virtual ICollection<Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle> Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
