//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario_Tipo
    {
        public Inventario_Tipo()
        {
            this.Marca_Tipo = new HashSet<Marca_Tipo>();
        }
    
        public int id_inventario_tipo { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Marca_Tipo> Marca_Tipo { get; set; }
    }
}
