//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs_Movimientos_Municion
    {
        public int id_log_mov_municion { get; set; }
        public Nullable<int> id_bodega_inventario_municion { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_bodega_origen { get; set; }
        public Nullable<int> id_bodega_destino { get; set; }
        public Nullable<int> id_tipo_transaccion { get; set; }
        public Nullable<int> id_estado_transaccion { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_asignacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> id_usuario_creacion { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<int> cantidad { get; set; }
    }
}
