//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipios
    {
        public Municipios()
        {
            this.Representante = new HashSet<Representante>();
            this.Representante1 = new HashSet<Representante>();
            this.Empleado_Direcciones = new HashSet<Empleado_Direcciones>();
            this.Empleado = new HashSet<Empleado>();
            this.Empleado1 = new HashSet<Empleado>();
            this.Ubicaciones = new HashSet<Ubicaciones>();
            this.Razones_Sociales = new HashSet<Razones_Sociales>();
            this.Razones_Sociales1 = new HashSet<Razones_Sociales>();
            this.Empresa = new HashSet<Empresa>();
        }
    
        public int id_municipio { get; set; }
        public int id_departamento { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public Nullable<int> codigo_dpi { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual ICollection<Representante> Representante { get; set; }
        public virtual ICollection<Representante> Representante1 { get; set; }
        public virtual ICollection<Empleado_Direcciones> Empleado_Direcciones { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual ICollection<Empleado> Empleado1 { get; set; }
        public virtual ICollection<Ubicaciones> Ubicaciones { get; set; }
        public virtual ICollection<Razones_Sociales> Razones_Sociales { get; set; }
        public virtual ICollection<Razones_Sociales> Razones_Sociales1 { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
