//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo
    {
        public Periodo()
        {
            this.Vacacion_Contrato = new HashSet<Vacacion_Contrato>();
            this.Vacacion_Contrato1 = new HashSet<Vacacion_Contrato>();
        }
    
        public int id_periodo { get; set; }
        public System.DateTime año_inicial { get; set; }
        public System.DateTime año_final { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public decimal salario_minimo { get; set; }
        public decimal bono_decreto { get; set; }
        public string definicion_salario { get; set; }
    
        public virtual ICollection<Vacacion_Contrato> Vacacion_Contrato { get; set; }
        public virtual ICollection<Vacacion_Contrato> Vacacion_Contrato1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
        public virtual Usuarios Usuarios3 { get; set; }
        public virtual Usuarios Usuarios4 { get; set; }
        public virtual Usuarios Usuarios5 { get; set; }
    }
}
