//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Porcentaje
    {
        public int id_porcentaje { get; set; }
        public Nullable<float> igss { get; set; }
        public Nullable<float> isr { get; set; }
        public Nullable<float> irtra { get; set; }
    }
}
