//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Porcentaje
    {
        public int id_porcentaje { get; set; }
        public Nullable<float> igss { get; set; }
        public Nullable<float> isr { get; set; }
        public Nullable<float> irtra { get; set; }
    }
}
