//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procesos_Facturacion
    {
        public Procesos_Facturacion()
        {
            this.Procesos_Facturacion_Detalle = new HashSet<Procesos_Facturacion_Detalle>();
            this.Gestion_Cobro = new HashSet<Gestion_Cobro>();
        }
    
        public int id_proceso_facturacion { get; set; }
        public System.DateTime fecha_proceso { get; set; }
        public int cantidad_detalles { get; set; }
        public decimal total_facturar { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
    
        public virtual ICollection<Procesos_Facturacion_Detalle> Procesos_Facturacion_Detalle { get; set; }
        public virtual ICollection<Gestion_Cobro> Gestion_Cobro { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
