//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Protal_webEntities : DbContext
    {
        public Protal_webEntities()
            : base("name=Protal_webEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pt_estadofuerza> pt_estadofuerza { get; set; }
        public virtual DbSet<pt_estadofuerza_encabezado> pt_estadofuerza_encabezado { get; set; }
        public virtual DbSet<pt_situacion> pt_situacion { get; set; }
        public virtual DbSet<pt_contratacion> pt_contratacion { get; set; }
        public virtual DbSet<pt_empleado> pt_empleado { get; set; }
        public virtual DbSet<pt_ubicacion> pt_ubicacion { get; set; }
        public virtual DbSet<pt_tipo_ubicacion> pt_tipo_ubicacion { get; set; }
        public virtual DbSet<Pt_Puestos> Pt_Puestos { get; set; }
        public virtual DbSet<Pt_Tipo_Pagos> Pt_Tipo_Pagos { get; set; }
        public virtual DbSet<Pt_Puesto_Insumos> Pt_Puesto_Insumos { get; set; }
        public virtual DbSet<Pt_Costos_Fijos> Pt_Costos_Fijos { get; set; }
        public virtual DbSet<Pt_Pagos_Puesto> Pt_Pagos_Puesto { get; set; }
        public virtual DbSet<Pt_Insumos> Pt_Insumos { get; set; }
        public virtual DbSet<Pt_Estados_Fase> Pt_Estados_Fase { get; set; }
        public virtual DbSet<Pt_Cotizaciones> Pt_Cotizaciones { get; set; }
        public virtual DbSet<Pt_Fases_Cotizacion> Pt_Fases_Cotizacion { get; set; }
        public virtual DbSet<Pt_Tipos_Proyecto> Pt_Tipos_Proyecto { get; set; }
        public virtual DbSet<Pt_Meses> Pt_Meses { get; set; }
        public virtual DbSet<Pt_Tipo_Gasto> Pt_Tipo_Gasto { get; set; }
        public virtual DbSet<Pt_Gastos_Costos_Fijos_Mes_Anio> Pt_Gastos_Costos_Fijos_Mes_Anio { get; set; }
        public virtual DbSet<Pt_Cantidad_Planilla_Mes_Anio> Pt_Cantidad_Planilla_Mes_Anio { get; set; }
        public virtual DbSet<Pt_Tmp_Cotizacion_Fase_Insumos> Pt_Tmp_Cotizacion_Fase_Insumos { get; set; }
        public virtual DbSet<Pt_Tmp_Cotizacion_Fase_Insumos_New> Pt_Tmp_Cotizacion_Fase_Insumos_New { get; set; }
        public virtual DbSet<Pt_Tmp_Propuesta_Fase_Puesto> Pt_Tmp_Propuesta_Fase_Puesto { get; set; }
        public virtual DbSet<Pt_Tmp_Cotizacion_Fase_Margen_Conf> Pt_Tmp_Cotizacion_Fase_Margen_Conf { get; set; }
        public virtual DbSet<Pt_Costos_Fijos_Mes_Anio> Pt_Costos_Fijos_Mes_Anio { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_ausentes_automatico(Nullable<int> id_encabezado, Nullable<System.DateTime> fechaInicio)
        {
            var id_encabezadoParameter = id_encabezado.HasValue ?
                new ObjectParameter("Id_encabezado", id_encabezado) :
                new ObjectParameter("Id_encabezado", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ausentes_automatico", id_encabezadoParameter, fechaInicioParameter);
        }
    
        [DbFunction("Protal_webEntities", "fn_detalle_estado_fuerza_dia")]
        public virtual IQueryable<fn_detalle_estado_fuerza_dia_Result> fn_detalle_estado_fuerza_dia(Nullable<System.DateTime> fecha_desde, Nullable<System.DateTime> fecha_hasta, Nullable<int> id_empleado)
        {
            var fecha_desdeParameter = fecha_desde.HasValue ?
                new ObjectParameter("fecha_desde", fecha_desde) :
                new ObjectParameter("fecha_desde", typeof(System.DateTime));
    
            var fecha_hastaParameter = fecha_hasta.HasValue ?
                new ObjectParameter("fecha_hasta", fecha_hasta) :
                new ObjectParameter("fecha_hasta", typeof(System.DateTime));
    
            var id_empleadoParameter = id_empleado.HasValue ?
                new ObjectParameter("id_empleado", id_empleado) :
                new ObjectParameter("id_empleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_detalle_estado_fuerza_dia_Result>("[Protal_webEntities].[fn_detalle_estado_fuerza_dia](@fecha_desde, @fecha_hasta, @id_empleado)", fecha_desdeParameter, fecha_hastaParameter, id_empleadoParameter);
        }
    
        public virtual int sp_ausentes_baja_automatico(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ausentes_baja_automatico", fechaParameter);
        }
    }
}
