//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pt_contratacion
    {
        public int PTCONTRATOID { get; set; }
        public int PTPRESTACIONID { get; set; }
        public int PTEMPLEADOID { get; set; }
        public int PTEMPRESAID { get; set; }
        public int PTCATEGORIAID { get; set; }
        public string NOMBRE_REFERIDO { get; set; }
        public Nullable<System.DateTime> FECHA_APRENDIZ { get; set; }
        public Nullable<System.DateTime> FECHA_APRENDIZ_FIN { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public Nullable<System.DateTime> FECHA_BAJA { get; set; }
        public string CAPACITACION { get; set; }
        public string OBSERVACIONES_ALTA { get; set; }
        public string OBSERVACIONES_BAJA { get; set; }
        public string MOTIVO_BAJA { get; set; }
        public string CREADO_POR { get; set; }
        public Nullable<System.DateTime> creado_el { get; set; }
        public string MODIFICADO_POR { get; set; }
        public Nullable<System.DateTime> modificado_el { get; set; }
        public string ESTADO { get; set; }
        public int PTCONTRATACIONID { get; set; }
        public Nullable<int> PTTIPOID { get; set; }
        public Nullable<int> PTAREAID { get; set; }
        public string OBSERVACIONES_APRENDIZ { get; set; }
    
        public virtual pt_empleado pt_empleado { get; set; }
    }
}
