//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pt_Cotizaciones
    {
        public Pt_Cotizaciones()
        {
            this.Pt_Fases_Cotizacion = new HashSet<Pt_Fases_Cotizacion>();
        }
    
        public int ccot_id { get; set; }
        public string ccot_nombre_proyecto { get; set; }
        public string ccot_descripcion_general { get; set; }
        public string ccot_contacto { get; set; }
        public Nullable<int> ccot_telefono_contacto { get; set; }
        public string ccot_correo_contacto { get; set; }
        public string ccot_direccion_contacto { get; set; }
        public Nullable<System.DateTime> ccot_fecha_entrega { get; set; }
        public Nullable<bool> ccot_finaliza_cotizacion { get; set; }
        public Nullable<System.DateTime> ccot_fecha_finalizacion { get; set; }
        public int id_usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public Nullable<int> ccot_id_usuario_finalizacion { get; set; }
        public Nullable<int> ccot_ctpo_id { get; set; }
    
        public virtual ICollection<Pt_Fases_Cotizacion> Pt_Fases_Cotizacion { get; set; }
        public virtual Pt_Tipos_Proyecto Pt_Tipos_Proyecto { get; set; }
    }
}
