//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pt_Costos_Fijos_Mes_Anio
    {
        public Pt_Costos_Fijos_Mes_Anio()
        {
            this.Pt_Gastos_Costos_Fijos_Mes_Anio = new HashSet<Pt_Gastos_Costos_Fijos_Mes_Anio>();
        }
    
        public int ccfma_id { get; set; }
        public string ccfma_descripcion { get; set; }
        public Nullable<int> ccfma_mes { get; set; }
        public Nullable<int> ccfma_anio { get; set; }
        public Nullable<decimal> ccfma_monto_gasto_administrativo { get; set; }
        public int id_usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public Nullable<decimal> ccfma_monto_gasto_operativo { get; set; }
    
        public virtual Pt_Meses Pt_Meses { get; set; }
        public virtual ICollection<Pt_Gastos_Costos_Fijos_Mes_Anio> Pt_Gastos_Costos_Fijos_Mes_Anio { get; set; }
    }
}
