//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pt_estadofuerza
    {
        public long pt_id { get; set; }
        public Nullable<int> ptempleadoid { get; set; }
        public Nullable<int> ptubicacionid { get; set; }
        public Nullable<int> pttipoid { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> modificado_el { get; set; }
        public Nullable<int> id_encabezado { get; set; }
        public string usuario_creacion { get; set; }
    
        public virtual pt_empleado pt_empleado { get; set; }
        public virtual pt_estadofuerza_encabezado pt_estadofuerza_encabezado { get; set; }
        public virtual pt_situacion pt_situacion { get; set; }
        public virtual pt_ubicacion pt_ubicacion { get; set; }
        public virtual pt_tipo_ubicacion pt_tipo_ubicacion { get; set; }
    }
}
