//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pt_empleado
    {
        public pt_empleado()
        {
            this.pt_estadofuerza = new HashSet<pt_estadofuerza>();
            this.pt_contratacion = new HashSet<pt_contratacion>();
        }
    
        public int PTEMPLEADOID { get; set; }
        public byte[] FOTO { get; set; }
        public string IDENTIFICACION { get; set; }
        public string CEDULA { get; set; }
        public string NOMBRE1 { get; set; }
        public string NOMBRE2 { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public string APELLIDO_CASADA { get; set; }
        public string SEXO { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string NIT { get; set; }
        public string NUMERO_IGSS { get; set; }
        public string NUMERO_IRTRA { get; set; }
        public Nullable<decimal> estatura { get; set; }
        public Nullable<decimal> peso { get; set; }
        public string DPI { get; set; }
        public string ESTADO { get; set; }
        public string NACIONALIDAD { get; set; }
        public string SERVICIO_MILITAR { get; set; }
        public string SABE_LEER { get; set; }
        public string SABE_ESCRIBIR { get; set; }
        public string DIR_NACIMIENTO { get; set; }
        public string MUN_NACIMIENTO { get; set; }
        public string DEPTO_NACIMIENTO { get; set; }
        public Nullable<int> ptescolaridadid { get; set; }
        public Nullable<int> ptprofesionid { get; set; }
        public string TIPOCUENTA { get; set; }
        public string CUENTA { get; set; }
        public string TELEFONO { get; set; }
        public string EXTENDIDA_EN { get; set; }
        public string CREADO_POR { get; set; }
        public Nullable<System.DateTime> creado_el { get; set; }
        public string MODIFICADO_POR { get; set; }
        public Nullable<System.DateTime> modificado_el { get; set; }
        public string tipo_licencia { get; set; }
        public string licencia { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public string cuadra { get; set; }
        public Nullable<int> ptcamaid { get; set; }
        public Nullable<int> PTBANCOID { get; set; }
    
        public virtual ICollection<pt_estadofuerza> pt_estadofuerza { get; set; }
        public virtual ICollection<pt_contratacion> pt_contratacion { get; set; }
    }
}
