//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pt_Fases_Cotizacion
    {
        public Pt_Fases_Cotizacion()
        {
            this.Pt_Tmp_Cotizacion_Fase_Insumos = new HashSet<Pt_Tmp_Cotizacion_Fase_Insumos>();
            this.Pt_Tmp_Cotizacion_Fase_Insumos_New = new HashSet<Pt_Tmp_Cotizacion_Fase_Insumos_New>();
            this.Pt_Tmp_Propuesta_Fase_Puesto = new HashSet<Pt_Tmp_Propuesta_Fase_Puesto>();
            this.Pt_Tmp_Cotizacion_Fase_Margen_Conf = new HashSet<Pt_Tmp_Cotizacion_Fase_Margen_Conf>();
        }
    
        public int cfas_id { get; set; }
        public string cfas_nombre { get; set; }
        public string cfas_descripcion { get; set; }
        public Nullable<System.DateTime> cfas_fecha_entrega { get; set; }
        public Nullable<int> cfas_cefa_id { get; set; }
        public Nullable<int> cfas_ccot_id { get; set; }
        public int id_usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public bool cfas_rev_ven { get; set; }
        public bool cfas_rev_ope { get; set; }
        public bool cfas_rev_gge { get; set; }
        public bool cfas_ok_ope { get; set; }
        public bool cfas_ok_ven { get; set; }
        public bool cfas_ok_gge { get; set; }
        public int cfas_id_usuario_ven { get; set; }
        public Nullable<int> cfas_id_usuario_ope { get; set; }
        public Nullable<int> cfas_id_usuario_gge { get; set; }
        public bool cfas_rc_gge { get; set; }
        public bool historico { get; set; }
    
        public virtual Pt_Cotizaciones Pt_Cotizaciones { get; set; }
        public virtual Pt_Estados_Fase Pt_Estados_Fase { get; set; }
        public virtual ICollection<Pt_Tmp_Cotizacion_Fase_Insumos> Pt_Tmp_Cotizacion_Fase_Insumos { get; set; }
        public virtual ICollection<Pt_Tmp_Cotizacion_Fase_Insumos_New> Pt_Tmp_Cotizacion_Fase_Insumos_New { get; set; }
        public virtual ICollection<Pt_Tmp_Propuesta_Fase_Puesto> Pt_Tmp_Propuesta_Fase_Puesto { get; set; }
        public virtual ICollection<Pt_Tmp_Cotizacion_Fase_Margen_Conf> Pt_Tmp_Cotizacion_Fase_Margen_Conf { get; set; }
    }
}
