//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pt_Gastos_Costos_Fijos_Mes_Anio
    {
        public int cgcf_id { get; set; }
        public Nullable<int> cgcf_ccfma_id { get; set; }
        public string cgcf_descripcion { get; set; }
        public Nullable<decimal> cgcf_precio_unitario { get; set; }
        public Nullable<int> cgcf_cantidad { get; set; }
        public Nullable<bool> cgcf_consumible { get; set; }
        public Nullable<bool> cgcf_depreciable { get; set; }
        public Nullable<decimal> cgcf_porcentaje_depreciacion { get; set; }
        public int id_usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
    
        public virtual Pt_Costos_Fijos_Mes_Anio Pt_Costos_Fijos_Mes_Anio { get; set; }
    }
}
