//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pt_Insumos
    {
        public Pt_Insumos()
        {
            this.Pt_Puesto_Insumos = new HashSet<Pt_Puesto_Insumos>();
            this.Pt_Tmp_Cotizacion_Fase_Insumos = new HashSet<Pt_Tmp_Cotizacion_Fase_Insumos>();
        }
    
        public int cins_id { get; set; }
        public string cins_descripcion { get; set; }
        public Nullable<decimal> cins_precio_costo { get; set; }
        public Nullable<decimal> cins_precio_venta { get; set; }
        public string cins_talla { get; set; }
        public Nullable<bool> cins_es_insumo { get; set; }
        public Nullable<bool> cins_es_arma { get; set; }
        public Nullable<bool> cins_es_uniforme { get; set; }
        public Nullable<bool> cins_depreciacion { get; set; }
        public int id_usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public Nullable<decimal> cins_porcentaje_depreciacion { get; set; }
    
        public virtual ICollection<Pt_Puesto_Insumos> Pt_Puesto_Insumos { get; set; }
        public virtual ICollection<Pt_Tmp_Cotizacion_Fase_Insumos> Pt_Tmp_Cotizacion_Fase_Insumos { get; set; }
    }
}
