//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pt_Pagos_Puesto
    {
        public int cppu_id { get; set; }
        public int cppu_ctpa_id { get; set; }
        public int cppu_cpue_id { get; set; }
        public Nullable<decimal> cppu_monto { get; set; }
        public Nullable<bool> cppu_salario_base { get; set; }
        public Nullable<decimal> cppu_porcentaje_calculo { get; set; }
        public int id_usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public string cppu_descripcion { get; set; }
        public Nullable<bool> cppu_depende_sb { get; set; }
    
        public virtual Pt_Puestos Pt_Puestos { get; set; }
        public virtual Pt_Tipo_Pagos Pt_Tipo_Pagos { get; set; }
    }
}
