//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pt_Tmp_Cotizacion_Fase_Insumos_New
    {
        public int ctpfin_id { get; set; }
        public string ctpfin_descripcion { get; set; }
        public Nullable<decimal> ctpfin_precio_costo { get; set; }
        public Nullable<decimal> ctpfin_precio_venta { get; set; }
        public string ctpfin_talla { get; set; }
        public Nullable<bool> ctpfin_es_insumo { get; set; }
        public Nullable<bool> ctpfin_es_arma { get; set; }
        public Nullable<bool> ctpfin_es_uniforme { get; set; }
        public Nullable<bool> ctpfin_depreciacion { get; set; }
        public Nullable<decimal> ctpfin_porcentaje_depreciacion { get; set; }
        public Nullable<int> ctpfin_cantidad { get; set; }
        public Nullable<int> ctpfin_cfas_id { get; set; }
        public int id_usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
    
        public virtual Pt_Fases_Cotizacion Pt_Fases_Cotizacion { get; set; }
    }
}
