//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pt_tipo_ubicacion
    {
        public pt_tipo_ubicacion()
        {
            this.pt_estadofuerza = new HashSet<pt_estadofuerza>();
        }
    
        public int PTTIPOID { get; set; }
        public string DESCRIPCION { get; set; }
        public string CREADO_POR { get; set; }
        public Nullable<System.DateTime> CREADO_EL { get; set; }
    
        public virtual ICollection<pt_estadofuerza> pt_estadofuerza { get; set; }
    }
}
