//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pt_ubicacion
    {
        public pt_ubicacion()
        {
            this.pt_estadofuerza = new HashSet<pt_estadofuerza>();
        }
    
        public int PTUBICACIONID { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<int> PTRAZONSOCIALID { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<int> CONTRATADOS { get; set; }
        public string CREADO_POR { get; set; }
        public Nullable<System.DateTime> CREADO_EL { get; set; }
        public string MODIFICADO_POR { get; set; }
        public Nullable<System.DateTime> MODIFICADO_EL { get; set; }
        public string ESTADO { get; set; }
        public string ENCARGADO { get; set; }
        public string responsable { get; set; }
    
        public virtual ICollection<pt_estadofuerza> pt_estadofuerza { get; set; }
    }
}
