//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puesto
    {
        public Puesto()
        {
            this.Contratacion = new HashSet<Contratacion>();
            this.Documento_Puesto = new HashSet<Documento_Puesto>();
        }
    
        public int id_puesto { get; set; }
        public decimal salario_minimo { get; set; }
        public decimal salario_maximo { get; set; }
        public string nombre { get; set; }
        public int id_tipo_puesto { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public decimal sueldo_base { get; set; }
        public decimal bono_decreto { get; set; }
        public decimal bono_extra { get; set; }
        public bool prestaciones { get; set; }
    
        public virtual Tipo_Puesto Tipo_Puesto { get; set; }
        public virtual ICollection<Contratacion> Contratacion { get; set; }
        public virtual ICollection<Documento_Puesto> Documento_Puesto { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
