//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Razones_Sociales
    {
        public Razones_Sociales()
        {
            this.Razon_Social_Contacto = new HashSet<Razon_Social_Contacto>();
            this.Contratos_Otros_Servicios = new HashSet<Contratos_Otros_Servicios>();
            this.Contratos_Agentes = new HashSet<Contratos_Agentes>();
            this.Contratos_Servicios = new HashSet<Contratos_Servicios>();
            this.Ubicaciones = new HashSet<Ubicaciones>();
            this.Razon_Social_Grupos_Factura = new HashSet<Razon_Social_Grupos_Factura>();
            this.Facturas = new HashSet<Facturas>();
            this.Procesos_Facturacion_Detalle = new HashSet<Procesos_Facturacion_Detalle>();
            this.Gestion_Cobro = new HashSet<Gestion_Cobro>();
        }
    
        public int id_razon_social { get; set; }
        public int id_cliente { get; set; }
        public string razon_social { get; set; }
        public string nombre_comercial { get; set; }
        public string nit { get; set; }
        public string direccion_fiscal { get; set; }
        public int municipio_direccion_fiscal { get; set; }
        public string direccion_facturacion { get; set; }
        public int municipio_direccion_facturacion { get; set; }
        public string descripcion_factura { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public int dias_credito { get; set; }
        public bool autogeneracion_factura { get; set; }
        public bool orden_aceptacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Municipios Municipios { get; set; }
        public virtual Municipios Municipios1 { get; set; }
        public virtual ICollection<Razon_Social_Contacto> Razon_Social_Contacto { get; set; }
        public virtual ICollection<Contratos_Otros_Servicios> Contratos_Otros_Servicios { get; set; }
        public virtual ICollection<Contratos_Agentes> Contratos_Agentes { get; set; }
        public virtual ICollection<Contratos_Servicios> Contratos_Servicios { get; set; }
        public virtual ICollection<Ubicaciones> Ubicaciones { get; set; }
        public virtual ICollection<Razon_Social_Grupos_Factura> Razon_Social_Grupos_Factura { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual ICollection<Procesos_Facturacion_Detalle> Procesos_Facturacion_Detalle { get; set; }
        public virtual ICollection<Gestion_Cobro> Gestion_Cobro { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
