//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte_Rol
    {
        public int id_reporte_rol { get; set; }
        public int id_reporte { get; set; }
        public int id_rol { get; set; }
    
        public virtual Reportes Reportes { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
