//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte_Carpeta
    {
        public Reporte_Carpeta()
        {
            this.Reportes = new HashSet<Reportes>();
        }
    
        public int id_reporte_carpeta { get; set; }
        public string nombre { get; set; }
        public string carpeta { get; set; }
    
        public virtual ICollection<Reportes> Reportes { get; set; }
    }
}
