//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reportes
    {
        public Reportes()
        {
            this.Reporte_Rol = new HashSet<Reporte_Rol>();
        }
    
        public int id_reporte { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string reporte { get; set; }
        public Nullable<int> id_reporte_carpeta { get; set; }
        public Nullable<int> id_reporte_grupo { get; set; }
        public string url { get; set; }
    
        public virtual Reporte_Carpeta Reporte_Carpeta { get; set; }
        public virtual ICollection<Reporte_Rol> Reporte_Rol { get; set; }
        public virtual Reporte_Grupo Reporte_Grupo { get; set; }
    }
}
