//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte_Grupo
    {
        public Reporte_Grupo()
        {
            this.Reportes = new HashSet<Reportes>();
        }
    
        public int id_reporte_grupo { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Reportes> Reportes { get; set; }
    }
}
