//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representante
    {
        public Representante()
        {
            this.Representante_Empresa = new HashSet<Representante_Empresa>();
        }
    
        public int id_representante { get; set; }
        public string primer_nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string apellido_casada { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public int id_estado_civil { get; set; }
        public int id_genero { get; set; }
        public string direccion { get; set; }
        public int id_municipio_direccion { get; set; }
        public long dpi { get; set; }
        public int id_municipio_dpi { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public int id_pais_nacionalidad { get; set; }
    
        public virtual Estado_Civil Estado_Civil { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Municipios Municipios { get; set; }
        public virtual Municipios Municipios1 { get; set; }
        public virtual Paises Paises { get; set; }
        public virtual ICollection<Representante_Empresa> Representante_Empresa { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
