//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Acciones
    {
        public int id_rol { get; set; }
        public int id_controlador { get; set; }
        public int id_accion { get; set; }
    
        public virtual Acciones Acciones { get; set; }
        public virtual Controladores Controladores { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
