//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Acciones
    {
        public int id_rol { get; set; }
        public int id_controlador { get; set; }
        public int id_accion { get; set; }
    
        public virtual Acciones Acciones { get; set; }
        public virtual Controladores Controladores { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
