//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.Reporte_Rol = new HashSet<Reporte_Rol>();
            this.Rol_Acciones = new HashSet<Rol_Acciones>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int id_rol { get; set; }
        public string nombre { get; set; }
        public int id_aplicacion { get; set; }
    
        public virtual Aplicaciones Aplicaciones { get; set; }
        public virtual ICollection<Reporte_Rol> Reporte_Rol { get; set; }
        public virtual ICollection<Rol_Acciones> Rol_Acciones { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
