//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Situacion
    {
        public Situacion()
        {
            this.Tipo_Permiso_Ausencia = new HashSet<Tipo_Permiso_Ausencia>();
            this.Estado_Fuerza_Detalle = new HashSet<Estado_Fuerza_Detalle>();
        }
    
        public int id_situacion { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public bool es_pago { get; set; }
        public int baja_rrhh { get; set; }
    
        public virtual ICollection<Tipo_Permiso_Ausencia> Tipo_Permiso_Ausencia { get; set; }
        public virtual ICollection<Estado_Fuerza_Detalle> Estado_Fuerza_Detalle { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
