//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Permiso_Ausencia
    {
        public Tipo_Permiso_Ausencia()
        {
            this.Empleado_Permisos_Ausencias = new HashSet<Empleado_Permisos_Ausencias>();
        }
    
        public int id_tipo_permiso_ausencia { get; set; }
        public string descripcion { get; set; }
        public int id_situacion { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
    
        public virtual Situacion Situacion { get; set; }
        public virtual ICollection<Empleado_Permisos_Ausencias> Empleado_Permisos_Ausencias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
        public virtual Usuarios Usuarios3 { get; set; }
        public virtual Usuarios Usuarios4 { get; set; }
        public virtual Usuarios Usuarios5 { get; set; }
    }
}
