//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion_Inventario_Detalle
    {
        public int id_transaccion_inventario_detalle { get; set; }
        public int id_transaccion_inventario { get; set; }
        public int id_transaccion_inventario_tipo { get; set; }
        public Nullable<int> id_arma { get; set; }
        public Nullable<int> id_municion { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<int> id_uniforme { get; set; }
        public Nullable<int> id_consumible { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> debe { get; set; }
        public Nullable<decimal> haber { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public Nullable<int> id_bodega { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Articulos Articulos { get; set; }
        public virtual Bodegas Bodegas { get; set; }
        public virtual Consumibles Consumibles { get; set; }
        public virtual Municiones Municiones { get; set; }
        public virtual Transacciones_Inventario Transacciones_Inventario { get; set; }
        public virtual Transaccion_Inventario_Tipo Transaccion_Inventario_Tipo { get; set; }
        public virtual Uniformes Uniformes { get; set; }
        public virtual Armas Armas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
