//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones
    {
        public Ubicaciones()
        {
            this.Contratacion = new HashSet<Contratacion>();
            this.Empleado_Encabezado_Planilla = new HashSet<Empleado_Encabezado_Planilla>();
            this.Estado_Fuerza_Detalle = new HashSet<Estado_Fuerza_Detalle>();
            this.Armas = new HashSet<Armas>();
            this.Contratos_Otros_Servicios = new HashSet<Contratos_Otros_Servicios>();
            this.Contratos_Agentes = new HashSet<Contratos_Agentes>();
            this.Procesos_Facturacion_Detalle = new HashSet<Procesos_Facturacion_Detalle>();
        }
    
        public int id_ubicacion { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public Nullable<int> id_municipio { get; set; }
        public int id_razon_social { get; set; }
        public Nullable<int> cantidad_solicitada { get; set; }
        public Nullable<int> cantidad_contratados { get; set; }
        public string id_contacto_encargado { get; set; }
        public string id_contacto_responsable { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
    
        public virtual Municipios Municipios { get; set; }
        public virtual Razones_Sociales Razones_Sociales { get; set; }
        public virtual ICollection<Contratacion> Contratacion { get; set; }
        public virtual ICollection<Empleado_Encabezado_Planilla> Empleado_Encabezado_Planilla { get; set; }
        public virtual ICollection<Estado_Fuerza_Detalle> Estado_Fuerza_Detalle { get; set; }
        public virtual ICollection<Armas> Armas { get; set; }
        public virtual ICollection<Contratos_Otros_Servicios> Contratos_Otros_Servicios { get; set; }
        public virtual ICollection<Contratos_Agentes> Contratos_Agentes { get; set; }
        public virtual ICollection<Procesos_Facturacion_Detalle> Procesos_Facturacion_Detalle { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
