//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Archivo = new HashSet<Archivo>();
            this.Archivo1 = new HashSet<Archivo>();
            this.Archivo2 = new HashSet<Archivo>();
            this.Banco = new HashSet<Banco>();
            this.Banco1 = new HashSet<Banco>();
            this.Banco2 = new HashSet<Banco>();
            this.Clientes = new HashSet<Clientes>();
            this.Clientes1 = new HashSet<Clientes>();
            this.Clientes2 = new HashSet<Clientes>();
            this.Compromisos = new HashSet<Compromisos>();
            this.Compromisos1 = new HashSet<Compromisos>();
            this.Compromisos2 = new HashSet<Compromisos>();
            this.Contacto_Puesto = new HashSet<Contacto_Puesto>();
            this.Contacto_Puesto1 = new HashSet<Contacto_Puesto>();
            this.Contacto_Puesto2 = new HashSet<Contacto_Puesto>();
            this.Contactos = new HashSet<Contactos>();
            this.Contactos1 = new HashSet<Contactos>();
            this.Contactos2 = new HashSet<Contactos>();
            this.Departamentos = new HashSet<Departamentos>();
            this.Departamentos1 = new HashSet<Departamentos>();
            this.Departamentos2 = new HashSet<Departamentos>();
            this.Dias_Semana = new HashSet<Dias_Semana>();
            this.Dias_Semana1 = new HashSet<Dias_Semana>();
            this.Dias_Semana2 = new HashSet<Dias_Semana>();
            this.Empresa = new HashSet<Empresa>();
            this.Empresa1 = new HashSet<Empresa>();
            this.Empresa2 = new HashSet<Empresa>();
            this.Empresa_Notorio = new HashSet<Empresa_Notorio>();
            this.Empresa_Notorio1 = new HashSet<Empresa_Notorio>();
            this.Empresa_Notorio2 = new HashSet<Empresa_Notorio>();
            this.Estado_Civil = new HashSet<Estado_Civil>();
            this.Estado_Civil1 = new HashSet<Estado_Civil>();
            this.Estado_Civil2 = new HashSet<Estado_Civil>();
            this.Genero = new HashSet<Genero>();
            this.Genero1 = new HashSet<Genero>();
            this.Genero2 = new HashSet<Genero>();
            this.Monedas = new HashSet<Monedas>();
            this.Monedas1 = new HashSet<Monedas>();
            this.Monedas2 = new HashSet<Monedas>();
            this.Municipios = new HashSet<Municipios>();
            this.Municipios1 = new HashSet<Municipios>();
            this.Municipios2 = new HashSet<Municipios>();
            this.Notorio = new HashSet<Notorio>();
            this.Notorio1 = new HashSet<Notorio>();
            this.Notorio2 = new HashSet<Notorio>();
            this.Paises = new HashSet<Paises>();
            this.Paises1 = new HashSet<Paises>();
            this.Paises2 = new HashSet<Paises>();
            this.Profesion = new HashSet<Profesion>();
            this.Profesion1 = new HashSet<Profesion>();
            this.Profesion2 = new HashSet<Profesion>();
            this.Razon_Social_Contacto = new HashSet<Razon_Social_Contacto>();
            this.Razon_Social_Contacto1 = new HashSet<Razon_Social_Contacto>();
            this.Razon_Social_Contacto2 = new HashSet<Razon_Social_Contacto>();
            this.Razon_Social_Grupos_Factura = new HashSet<Razon_Social_Grupos_Factura>();
            this.Razon_Social_Grupos_Factura1 = new HashSet<Razon_Social_Grupos_Factura>();
            this.Razon_Social_Grupos_Factura2 = new HashSet<Razon_Social_Grupos_Factura>();
            this.Razones_Sociales = new HashSet<Razones_Sociales>();
            this.Razones_Sociales1 = new HashSet<Razones_Sociales>();
            this.Razones_Sociales2 = new HashSet<Razones_Sociales>();
            this.Representante = new HashSet<Representante>();
            this.Representante1 = new HashSet<Representante>();
            this.Representante2 = new HashSet<Representante>();
            this.Representante_Empresa = new HashSet<Representante_Empresa>();
            this.Representante_Empresa1 = new HashSet<Representante_Empresa>();
            this.Representante_Empresa2 = new HashSet<Representante_Empresa>();
            this.Tipo_Archivo = new HashSet<Tipo_Archivo>();
            this.Tipo_Archivo1 = new HashSet<Tipo_Archivo>();
            this.Tipo_Archivo2 = new HashSet<Tipo_Archivo>();
            this.Tipo_Cliente = new HashSet<Tipo_Cliente>();
            this.Tipo_Cliente1 = new HashSet<Tipo_Cliente>();
            this.Tipo_Cliente2 = new HashSet<Tipo_Cliente>();
            this.Tipo_Cuenta = new HashSet<Tipo_Cuenta>();
            this.Tipo_Cuenta1 = new HashSet<Tipo_Cuenta>();
            this.Tipo_Cuenta2 = new HashSet<Tipo_Cuenta>();
            this.Tipo_Direccion = new HashSet<Tipo_Direccion>();
            this.Tipo_Direccion1 = new HashSet<Tipo_Direccion>();
            this.Tipo_Direccion2 = new HashSet<Tipo_Direccion>();
            this.Tipo_Licencia = new HashSet<Tipo_Licencia>();
            this.Tipo_Licencia1 = new HashSet<Tipo_Licencia>();
            this.Tipo_Licencia2 = new HashSet<Tipo_Licencia>();
            this.Tipo_Servicio = new HashSet<Tipo_Servicio>();
            this.Tipo_Servicio1 = new HashSet<Tipo_Servicio>();
            this.Tipo_Servicio2 = new HashSet<Tipo_Servicio>();
            this.Tipo_Telefono = new HashSet<Tipo_Telefono>();
            this.Tipo_Telefono1 = new HashSet<Tipo_Telefono>();
            this.Tipo_Telefono2 = new HashSet<Tipo_Telefono>();
            this.Ubicaciones = new HashSet<Ubicaciones>();
            this.Ubicaciones1 = new HashSet<Ubicaciones>();
            this.Ubicaciones2 = new HashSet<Ubicaciones>();
            this.Cat_Estado_Proceso_Facturacion_Detalle = new HashSet<Cat_Estado_Proceso_Facturacion_Detalle>();
            this.Cat_Estado_Proceso_Facturacion_Detalle1 = new HashSet<Cat_Estado_Proceso_Facturacion_Detalle>();
            this.Cat_Estado_Proceso_Facturacion_Detalle2 = new HashSet<Cat_Estado_Proceso_Facturacion_Detalle>();
            this.Cat_Razones_Anulacion = new HashSet<Cat_Razones_Anulacion>();
            this.Cat_Razones_Anulacion1 = new HashSet<Cat_Razones_Anulacion>();
            this.Cat_Razones_Anulacion2 = new HashSet<Cat_Razones_Anulacion>();
            this.Cat_Razones_Eliminacion = new HashSet<Cat_Razones_Eliminacion>();
            this.Cat_Razones_Eliminacion1 = new HashSet<Cat_Razones_Eliminacion>();
            this.Cat_Razones_Eliminacion2 = new HashSet<Cat_Razones_Eliminacion>();
            this.Contratos_Servicios = new HashSet<Contratos_Servicios>();
            this.Contratos_Servicios1 = new HashSet<Contratos_Servicios>();
            this.Contratos_Servicios2 = new HashSet<Contratos_Servicios>();
            this.Cat_Estados_Factura = new HashSet<Cat_Estados_Factura>();
            this.Cat_Estados_Factura1 = new HashSet<Cat_Estados_Factura>();
            this.Cat_Estados_Factura2 = new HashSet<Cat_Estados_Factura>();
            this.Cat_Estados_Servicio_Contratado = new HashSet<Cat_Estados_Servicio_Contratado>();
            this.Cat_Estados_Servicio_Contratado1 = new HashSet<Cat_Estados_Servicio_Contratado>();
            this.Cat_Estados_Servicio_Contratado2 = new HashSet<Cat_Estados_Servicio_Contratado>();
            this.Facturas = new HashSet<Facturas>();
            this.Facturas1 = new HashSet<Facturas>();
            this.Facturas2 = new HashSet<Facturas>();
            this.Facturas_Detalle = new HashSet<Facturas_Detalle>();
            this.Facturas_Detalle1 = new HashSet<Facturas_Detalle>();
            this.Facturas_Detalle2 = new HashSet<Facturas_Detalle>();
            this.Archivo_Empleado = new HashSet<Archivo_Empleado>();
            this.Archivo_Empleado1 = new HashSet<Archivo_Empleado>();
            this.Archivo_Empleado2 = new HashSet<Archivo_Empleado>();
            this.Asistencias_Extras_Empleado = new HashSet<Asistencias_Extras_Empleado>();
            this.Asistencias_Extras_Empleado1 = new HashSet<Asistencias_Extras_Empleado>();
            this.Asistencias_Extras_Empleado2 = new HashSet<Asistencias_Extras_Empleado>();
            this.Bonificacion = new HashSet<Bonificacion>();
            this.Bonificacion1 = new HashSet<Bonificacion>();
            this.Bonificacion2 = new HashSet<Bonificacion>();
            this.Capacitacion_Impartida = new HashSet<Capacitacion_Impartida>();
            this.Capacitacion_Impartida1 = new HashSet<Capacitacion_Impartida>();
            this.Capacitacion_Impartida2 = new HashSet<Capacitacion_Impartida>();
            this.Capacitacion_Impartida3 = new HashSet<Capacitacion_Impartida>();
            this.Capacitacion_Impartida4 = new HashSet<Capacitacion_Impartida>();
            this.Capacitacion_Impartida5 = new HashSet<Capacitacion_Impartida>();
            this.Carga_Estado_Fuerza = new HashSet<Carga_Estado_Fuerza>();
            this.Cat_Otros_Servicios = new HashSet<Cat_Otros_Servicios>();
            this.Cat_Otros_Servicios1 = new HashSet<Cat_Otros_Servicios>();
            this.Cat_Otros_Servicios2 = new HashSet<Cat_Otros_Servicios>();
            this.Cat_Tipos_Gestion = new HashSet<Cat_Tipos_Gestion>();
            this.Cat_Tipos_Gestion1 = new HashSet<Cat_Tipos_Gestion>();
            this.Cat_Tipos_Gestion2 = new HashSet<Cat_Tipos_Gestion>();
            this.Cat_Tipos_Respuesta_Gestion = new HashSet<Cat_Tipos_Respuesta_Gestion>();
            this.Cat_Tipos_Respuesta_Gestion1 = new HashSet<Cat_Tipos_Respuesta_Gestion>();
            this.Cat_Tipos_Respuesta_Gestion2 = new HashSet<Cat_Tipos_Respuesta_Gestion>();
            this.Cat_Tipos_Respuesta_Gestion3 = new HashSet<Cat_Tipos_Respuesta_Gestion>();
            this.Cat_Tipos_Respuesta_Gestion4 = new HashSet<Cat_Tipos_Respuesta_Gestion>();
            this.Cat_Tipos_Respuesta_Gestion5 = new HashSet<Cat_Tipos_Respuesta_Gestion>();
            this.Contratos_Otros_Servicios = new HashSet<Contratos_Otros_Servicios>();
            this.Contratos_Otros_Servicios1 = new HashSet<Contratos_Otros_Servicios>();
            this.Contratos_Otros_Servicios2 = new HashSet<Contratos_Otros_Servicios>();
            this.Contratos_Agentes = new HashSet<Contratos_Agentes>();
            this.Contratos_Agentes1 = new HashSet<Contratos_Agentes>();
            this.Contratos_Agentes2 = new HashSet<Contratos_Agentes>();
            this.Curso_Empleado = new HashSet<Curso_Empleado>();
            this.Curso_Empleado1 = new HashSet<Curso_Empleado>();
            this.Curso_Empleado2 = new HashSet<Curso_Empleado>();
            this.Descuento = new HashSet<Descuento>();
            this.Descuento1 = new HashSet<Descuento>();
            this.Descuento2 = new HashSet<Descuento>();
            this.Descuento_Periodico = new HashSet<Descuento_Periodico>();
            this.Descuento_Periodico1 = new HashSet<Descuento_Periodico>();
            this.Descuento_Periodico2 = new HashSet<Descuento_Periodico>();
            this.Documentos = new HashSet<Documentos>();
            this.Documentos1 = new HashSet<Documentos>();
            this.Documentos2 = new HashSet<Documentos>();
            this.Documento_Puesto = new HashSet<Documento_Puesto>();
            this.Documento_Puesto1 = new HashSet<Documento_Puesto>();
            this.Documento_Puesto2 = new HashSet<Documento_Puesto>();
            this.Empleado_Encabezado_Planilla = new HashSet<Empleado_Encabezado_Planilla>();
            this.Empleado_Encabezado_Planilla1 = new HashSet<Empleado_Encabezado_Planilla>();
            this.Empleado_Encabezado_Planilla2 = new HashSet<Empleado_Encabezado_Planilla>();
            this.Empleado_Encabezado_Planilla3 = new HashSet<Empleado_Encabezado_Planilla>();
            this.Empleado_Encabezado_Planilla4 = new HashSet<Empleado_Encabezado_Planilla>();
            this.Empleado_Encabezado_Planilla5 = new HashSet<Empleado_Encabezado_Planilla>();
            this.Empleado_Permisos_Ausencias = new HashSet<Empleado_Permisos_Ausencias>();
            this.Empleado_Permisos_Ausencias1 = new HashSet<Empleado_Permisos_Ausencias>();
            this.Empleado_Permisos_Ausencias2 = new HashSet<Empleado_Permisos_Ausencias>();
            this.Empleado_Experiencia_Laboral = new HashSet<Empleado_Experiencia_Laboral>();
            this.Empleado_Experiencia_Laboral1 = new HashSet<Empleado_Experiencia_Laboral>();
            this.Empleado_Experiencia_Laboral2 = new HashSet<Empleado_Experiencia_Laboral>();
            this.Empleado = new HashSet<Empleado>();
            this.Empleado1 = new HashSet<Empleado>();
            this.Empleado2 = new HashSet<Empleado>();
            this.Encabezado_Planilla = new HashSet<Encabezado_Planilla>();
            this.Encabezado_Planilla1 = new HashSet<Encabezado_Planilla>();
            this.Encabezado_Planilla2 = new HashSet<Encabezado_Planilla>();
            this.Encabezado_Planilla3 = new HashSet<Encabezado_Planilla>();
            this.Encabezado_Planilla4 = new HashSet<Encabezado_Planilla>();
            this.Estado_Empleado = new HashSet<Estado_Empleado>();
            this.Estado_Empleado1 = new HashSet<Estado_Empleado>();
            this.Estado_Empleado2 = new HashSet<Estado_Empleado>();
            this.Estado_Fuerza = new HashSet<Estado_Fuerza>();
            this.Estado_Fuerza1 = new HashSet<Estado_Fuerza>();
            this.Estado_Fuerza2 = new HashSet<Estado_Fuerza>();
            this.Estado_Fuerza3 = new HashSet<Estado_Fuerza>();
            this.Estado_Fuerza_Detalle = new HashSet<Estado_Fuerza_Detalle>();
            this.Estado_Fuerza_Detalle1 = new HashSet<Estado_Fuerza_Detalle>();
            this.Estado_Fuerza_Detalle2 = new HashSet<Estado_Fuerza_Detalle>();
            this.Gestion_Cobro = new HashSet<Gestion_Cobro>();
            this.Gestion_Cobro1 = new HashSet<Gestion_Cobro>();
            this.Gestion_Cobro2 = new HashSet<Gestion_Cobro>();
            this.Gestion_Cobro_Detalle = new HashSet<Gestion_Cobro_Detalle>();
            this.Gestion_Cobro_Detalle1 = new HashSet<Gestion_Cobro_Detalle>();
            this.Gestion_Cobro_Detalle2 = new HashSet<Gestion_Cobro_Detalle>();
            this.Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle = new HashSet<Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle>();
            this.Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle1 = new HashSet<Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle>();
            this.Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle2 = new HashSet<Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle>();
            this.Grado_Estudio = new HashSet<Grado_Estudio>();
            this.Grado_Estudio1 = new HashSet<Grado_Estudio>();
            this.Grado_Estudio2 = new HashSet<Grado_Estudio>();
            this.Motivo_Baja = new HashSet<Motivo_Baja>();
            this.Motivo_Baja1 = new HashSet<Motivo_Baja>();
            this.Motivo_Baja2 = new HashSet<Motivo_Baja>();
            this.Periodo = new HashSet<Periodo>();
            this.Periodo1 = new HashSet<Periodo>();
            this.Periodo2 = new HashSet<Periodo>();
            this.Periodo3 = new HashSet<Periodo>();
            this.Periodo4 = new HashSet<Periodo>();
            this.Periodo5 = new HashSet<Periodo>();
            this.Planilla = new HashSet<Planilla>();
            this.Planilla1 = new HashSet<Planilla>();
            this.Planilla2 = new HashSet<Planilla>();
            this.Salario = new HashSet<Salario>();
            this.Salario1 = new HashSet<Salario>();
            this.Salario2 = new HashSet<Salario>();
            this.Situacion = new HashSet<Situacion>();
            this.Situacion1 = new HashSet<Situacion>();
            this.Situacion2 = new HashSet<Situacion>();
            this.Tipo_Bono = new HashSet<Tipo_Bono>();
            this.Tipo_Bono1 = new HashSet<Tipo_Bono>();
            this.Tipo_Bono2 = new HashSet<Tipo_Bono>();
            this.Tipo_Descuento = new HashSet<Tipo_Descuento>();
            this.Tipo_Descuento1 = new HashSet<Tipo_Descuento>();
            this.Tipo_Descuento2 = new HashSet<Tipo_Descuento>();
            this.Tipo_Pago = new HashSet<Tipo_Pago>();
            this.Tipo_Pago1 = new HashSet<Tipo_Pago>();
            this.Tipo_Pago2 = new HashSet<Tipo_Pago>();
            this.Tipo_Permiso_Ausencia = new HashSet<Tipo_Permiso_Ausencia>();
            this.Tipo_Permiso_Ausencia1 = new HashSet<Tipo_Permiso_Ausencia>();
            this.Tipo_Permiso_Ausencia2 = new HashSet<Tipo_Permiso_Ausencia>();
            this.Tipo_Permiso_Ausencia3 = new HashSet<Tipo_Permiso_Ausencia>();
            this.Tipo_Permiso_Ausencia4 = new HashSet<Tipo_Permiso_Ausencia>();
            this.Tipo_Permiso_Ausencia5 = new HashSet<Tipo_Permiso_Ausencia>();
            this.Tipo_Planilla = new HashSet<Tipo_Planilla>();
            this.Tipo_Planilla1 = new HashSet<Tipo_Planilla>();
            this.Tipo_Planilla2 = new HashSet<Tipo_Planilla>();
            this.Tipo_Plan_Pago = new HashSet<Tipo_Plan_Pago>();
            this.Tipo_Plan_Pago1 = new HashSet<Tipo_Plan_Pago>();
            this.Tipo_Plan_Pago2 = new HashSet<Tipo_Plan_Pago>();
            this.Tipo_Prestamo = new HashSet<Tipo_Prestamo>();
            this.Tipo_Prestamo1 = new HashSet<Tipo_Prestamo>();
            this.Tipo_Prestamo2 = new HashSet<Tipo_Prestamo>();
            this.Tipo_Puesto = new HashSet<Tipo_Puesto>();
            this.Tipo_Puesto1 = new HashSet<Tipo_Puesto>();
            this.Tipo_Puesto2 = new HashSet<Tipo_Puesto>();
            this.Vacacion_Contrato = new HashSet<Vacacion_Contrato>();
            this.Vacacion_Contrato1 = new HashSet<Vacacion_Contrato>();
            this.Vacacion_Contrato2 = new HashSet<Vacacion_Contrato>();
            this.Vacacion_Contrato3 = new HashSet<Vacacion_Contrato>();
            this.Vacacion_Contrato4 = new HashSet<Vacacion_Contrato>();
            this.Vacacion_Contrato5 = new HashSet<Vacacion_Contrato>();
            this.Vacacion_Detalle = new HashSet<Vacacion_Detalle>();
            this.Vacacion_Detalle1 = new HashSet<Vacacion_Detalle>();
            this.Vacacion_Detalle2 = new HashSet<Vacacion_Detalle>();
            this.Academia = new HashSet<Academia>();
            this.Academia1 = new HashSet<Academia>();
            this.Academia2 = new HashSet<Academia>();
            this.Aprendiz = new HashSet<Aprendiz>();
            this.Aprendiz1 = new HashSet<Aprendiz>();
            this.Aprendiz2 = new HashSet<Aprendiz>();
            this.Arma_Estado_Policia = new HashSet<Arma_Estado_Policia>();
            this.Arma_Estado_Policia1 = new HashSet<Arma_Estado_Policia>();
            this.Arma_Estado_Policia2 = new HashSet<Arma_Estado_Policia>();
            this.Arma_Estado = new HashSet<Arma_Estado>();
            this.Arma_Estado1 = new HashSet<Arma_Estado>();
            this.Arma_Estado2 = new HashSet<Arma_Estado>();
            this.Arma_Tipo = new HashSet<Arma_Tipo>();
            this.Arma_Tipo1 = new HashSet<Arma_Tipo>();
            this.Arma_Tipo2 = new HashSet<Arma_Tipo>();
            this.Armas = new HashSet<Armas>();
            this.Armas1 = new HashSet<Armas>();
            this.Armas2 = new HashSet<Armas>();
            this.Articulo_Tipo = new HashSet<Articulo_Tipo>();
            this.Articulo_Tipo1 = new HashSet<Articulo_Tipo>();
            this.Articulo_Tipo2 = new HashSet<Articulo_Tipo>();
            this.Articulos = new HashSet<Articulos>();
            this.Articulos1 = new HashSet<Articulos>();
            this.Articulos2 = new HashSet<Articulos>();
            this.Bodega_Inventario_Consumibles = new HashSet<Bodega_Inventario_Consumibles>();
            this.Bodega_Inventario_Consumibles1 = new HashSet<Bodega_Inventario_Consumibles>();
            this.Bodega_Inventario_Consumibles2 = new HashSet<Bodega_Inventario_Consumibles>();
            this.Bodega_Inventario_Municiones = new HashSet<Bodega_Inventario_Municiones>();
            this.Bodega_Inventario_Municiones1 = new HashSet<Bodega_Inventario_Municiones>();
            this.Bodega_Inventario_Municiones2 = new HashSet<Bodega_Inventario_Municiones>();
            this.Bodega_Inventario_Uniformes = new HashSet<Bodega_Inventario_Uniformes>();
            this.Bodega_Inventario_Uniformes1 = new HashSet<Bodega_Inventario_Uniformes>();
            this.Bodega_Inventario_Uniformes2 = new HashSet<Bodega_Inventario_Uniformes>();
            this.Bodegas = new HashSet<Bodegas>();
            this.Bodegas1 = new HashSet<Bodegas>();
            this.Bodegas2 = new HashSet<Bodegas>();
            this.Calibres = new HashSet<Calibres>();
            this.Calibres1 = new HashSet<Calibres>();
            this.Calibres2 = new HashSet<Calibres>();
            this.Capacitacion_Curso = new HashSet<Capacitacion_Curso>();
            this.Capacitacion_Curso1 = new HashSet<Capacitacion_Curso>();
            this.Capacitacion_Curso2 = new HashSet<Capacitacion_Curso>();
            this.Capacitacion = new HashSet<Capacitacion>();
            this.Capacitacion1 = new HashSet<Capacitacion>();
            this.Capacitacion2 = new HashSet<Capacitacion>();
            this.Consumible_Tipo = new HashSet<Consumible_Tipo>();
            this.Consumible_Tipo1 = new HashSet<Consumible_Tipo>();
            this.Consumible_Tipo2 = new HashSet<Consumible_Tipo>();
            this.Consumibles = new HashSet<Consumibles>();
            this.Consumibles1 = new HashSet<Consumibles>();
            this.Consumibles2 = new HashSet<Consumibles>();
            this.Contratacion = new HashSet<Contratacion>();
            this.Contratacion1 = new HashSet<Contratacion>();
            this.Contratacion2 = new HashSet<Contratacion>();
            this.Curso = new HashSet<Curso>();
            this.Curso1 = new HashSet<Curso>();
            this.Curso2 = new HashSet<Curso>();
            this.Egreso_Estado = new HashSet<Egreso_Estado>();
            this.Egreso_Estado1 = new HashSet<Egreso_Estado>();
            this.Egreso_Estado2 = new HashSet<Egreso_Estado>();
            this.Egreso_Tipo = new HashSet<Egreso_Tipo>();
            this.Egreso_Tipo1 = new HashSet<Egreso_Tipo>();
            this.Egreso_Tipo2 = new HashSet<Egreso_Tipo>();
            this.Empleado_Direcciones = new HashSet<Empleado_Direcciones>();
            this.Empleado_Direcciones1 = new HashSet<Empleado_Direcciones>();
            this.Empleado_Direcciones2 = new HashSet<Empleado_Direcciones>();
            this.Empleado_Telefono = new HashSet<Empleado_Telefono>();
            this.Empleado_Telefono1 = new HashSet<Empleado_Telefono>();
            this.Empleado_Telefono2 = new HashSet<Empleado_Telefono>();
            this.Ingreso_Estado = new HashSet<Ingreso_Estado>();
            this.Ingreso_Estado1 = new HashSet<Ingreso_Estado>();
            this.Ingreso_Estado2 = new HashSet<Ingreso_Estado>();
            this.Instructor = new HashSet<Instructor>();
            this.Instructor1 = new HashSet<Instructor>();
            this.Instructor2 = new HashSet<Instructor>();
            this.Marca_Tipo = new HashSet<Marca_Tipo>();
            this.Marca_Tipo1 = new HashSet<Marca_Tipo>();
            this.Marca_Tipo2 = new HashSet<Marca_Tipo>();
            this.Marcas = new HashSet<Marcas>();
            this.Marcas1 = new HashSet<Marcas>();
            this.Marcas2 = new HashSet<Marcas>();
            this.Modelos = new HashSet<Modelos>();
            this.Modelos1 = new HashSet<Modelos>();
            this.Modelos2 = new HashSet<Modelos>();
            this.Municiones = new HashSet<Municiones>();
            this.Municiones1 = new HashSet<Municiones>();
            this.Municiones2 = new HashSet<Municiones>();
            this.Proveedores = new HashSet<Proveedores>();
            this.Proveedores1 = new HashSet<Proveedores>();
            this.Proveedores2 = new HashSet<Proveedores>();
            this.Puesto = new HashSet<Puesto>();
            this.Puesto1 = new HashSet<Puesto>();
            this.Puesto2 = new HashSet<Puesto>();
            this.Liquidaciones = new HashSet<Liquidaciones>();
            this.Liquidaciones1 = new HashSet<Liquidaciones>();
            this.Liquidaciones2 = new HashSet<Liquidaciones>();
            this.Transaccion_Inventario_Tipo = new HashSet<Transaccion_Inventario_Tipo>();
            this.Transaccion_Inventario_Tipo1 = new HashSet<Transaccion_Inventario_Tipo>();
            this.Transaccion_Inventario_Tipo2 = new HashSet<Transaccion_Inventario_Tipo>();
            this.Transaccion_Inventario_Detalle = new HashSet<Transaccion_Inventario_Detalle>();
            this.Transaccion_Inventario_Detalle1 = new HashSet<Transaccion_Inventario_Detalle>();
            this.Transaccion_Inventario_Detalle2 = new HashSet<Transaccion_Inventario_Detalle>();
            this.Transacciones_Inventario = new HashSet<Transacciones_Inventario>();
            this.Transacciones_Inventario1 = new HashSet<Transacciones_Inventario>();
            this.Transacciones_Inventario2 = new HashSet<Transacciones_Inventario>();
            this.Traslado_Estado = new HashSet<Traslado_Estado>();
            this.Traslado_Estado1 = new HashSet<Traslado_Estado>();
            this.Traslado_Estado2 = new HashSet<Traslado_Estado>();
            this.Uniforme_Tipo = new HashSet<Uniforme_Tipo>();
            this.Uniforme_Tipo1 = new HashSet<Uniforme_Tipo>();
            this.Uniforme_Tipo2 = new HashSet<Uniforme_Tipo>();
            this.Uniformes = new HashSet<Uniformes>();
            this.Uniformes1 = new HashSet<Uniformes>();
            this.Uniformes2 = new HashSet<Uniformes>();
            this.Procesos_Facturacion = new HashSet<Procesos_Facturacion>();
            this.Procesos_Facturacion1 = new HashSet<Procesos_Facturacion>();
            this.Procesos_Facturacion2 = new HashSet<Procesos_Facturacion>();
            this.Procesos_Facturacion_Detalle = new HashSet<Procesos_Facturacion_Detalle>();
            this.Procesos_Facturacion_Detalle1 = new HashSet<Procesos_Facturacion_Detalle>();
            this.Procesos_Facturacion_Detalle2 = new HashSet<Procesos_Facturacion_Detalle>();
            this.Series_Facturas = new HashSet<Series_Facturas>();
            this.Series_Facturas1 = new HashSet<Series_Facturas>();
            this.Series_Facturas2 = new HashSet<Series_Facturas>();
            this.Cat_Tipos_Agente = new HashSet<Cat_Tipos_Agente>();
            this.Cat_Tipos_Agente1 = new HashSet<Cat_Tipos_Agente>();
            this.Cat_Tipos_Agente2 = new HashSet<Cat_Tipos_Agente>();
            this.Cat_Tipos_Facturacion = new HashSet<Cat_Tipos_Facturacion>();
            this.Cat_Tipos_Facturacion1 = new HashSet<Cat_Tipos_Facturacion>();
            this.Cat_Tipos_Facturacion2 = new HashSet<Cat_Tipos_Facturacion>();
            this.Tickets_Generacion = new HashSet<Tickets_Generacion>();
            this.Tickets_Generacion1 = new HashSet<Tickets_Generacion>();
            this.Tickets_Generacion2 = new HashSet<Tickets_Generacion>();
            this.Tickets_Inventario = new HashSet<Tickets_Inventario>();
            this.Tickets_Inventario1 = new HashSet<Tickets_Inventario>();
            this.Tickets_Inventario2 = new HashSet<Tickets_Inventario>();
            this.Tickets_Inventario3 = new HashSet<Tickets_Inventario>();
            this.Tickets_Movimiento = new HashSet<Tickets_Movimiento>();
            this.Tickets_Movimiento1 = new HashSet<Tickets_Movimiento>();
            this.Tickets_Movimiento2 = new HashSet<Tickets_Movimiento>();
            this.Tickets_Movimiento3 = new HashSet<Tickets_Movimiento>();
            this.Tickets_Tipo = new HashSet<Tickets_Tipo>();
            this.Tickets_Tipo1 = new HashSet<Tickets_Tipo>();
            this.Tickets_Tipo2 = new HashSet<Tickets_Tipo>();
            this.Tickets_Tipo_Movimiento = new HashSet<Tickets_Tipo_Movimiento>();
            this.Tickets_Tipo_Movimiento1 = new HashSet<Tickets_Tipo_Movimiento>();
            this.Tickets_Tipo_Movimiento2 = new HashSet<Tickets_Tipo_Movimiento>();
            this.Roles = new HashSet<Roles>();
            this.Egreso_Detalle = new HashSet<Egreso_Detalle>();
            this.Egreso_Detalle1 = new HashSet<Egreso_Detalle>();
            this.Egreso_Detalle2 = new HashSet<Egreso_Detalle>();
            this.Egresos = new HashSet<Egresos>();
            this.Egresos1 = new HashSet<Egresos>();
            this.Egresos2 = new HashSet<Egresos>();
            this.Egresos3 = new HashSet<Egresos>();
            this.Ingreso_Detalle = new HashSet<Ingreso_Detalle>();
            this.Ingreso_Detalle1 = new HashSet<Ingreso_Detalle>();
            this.Ingreso_Detalle2 = new HashSet<Ingreso_Detalle>();
            this.Ingresos = new HashSet<Ingresos>();
            this.Ingresos1 = new HashSet<Ingresos>();
            this.Ingresos2 = new HashSet<Ingresos>();
            this.Ingresos3 = new HashSet<Ingresos>();
            this.Traslado_Detalle = new HashSet<Traslado_Detalle>();
            this.Traslado_Detalle1 = new HashSet<Traslado_Detalle>();
            this.Traslado_Detalle2 = new HashSet<Traslado_Detalle>();
            this.Traslados = new HashSet<Traslados>();
            this.Traslados1 = new HashSet<Traslados>();
            this.Traslados2 = new HashSet<Traslados>();
            this.Traslados3 = new HashSet<Traslados>();
        }
    
        public int id_usuario { get; set; }
        public string email { get; set; }
        public bool email_confirmado { get; set; }
        public string password_hash { get; set; }
        public string seguridad_stamp { get; set; }
        public bool two_factor_enabled { get; set; }
        public Nullable<System.DateTime> fecha_final_bloqueo_utc { get; set; }
        public bool bloqueo_habilitado { get; set; }
        public int conteo_accesos_fallidos { get; set; }
        public string usuario { get; set; }
        public string nombre_completo_usuario { get; set; }
        public string telefono_trabajo { get; set; }
        public string telefono_movil { get; set; }
        public bool usuario_externo { get; set; }
        public bool eliminado { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
    
        public virtual ICollection<Archivo> Archivo { get; set; }
        public virtual ICollection<Archivo> Archivo1 { get; set; }
        public virtual ICollection<Archivo> Archivo2 { get; set; }
        public virtual ICollection<Banco> Banco { get; set; }
        public virtual ICollection<Banco> Banco1 { get; set; }
        public virtual ICollection<Banco> Banco2 { get; set; }
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual ICollection<Clientes> Clientes1 { get; set; }
        public virtual ICollection<Clientes> Clientes2 { get; set; }
        public virtual ICollection<Compromisos> Compromisos { get; set; }
        public virtual ICollection<Compromisos> Compromisos1 { get; set; }
        public virtual ICollection<Compromisos> Compromisos2 { get; set; }
        public virtual ICollection<Contacto_Puesto> Contacto_Puesto { get; set; }
        public virtual ICollection<Contacto_Puesto> Contacto_Puesto1 { get; set; }
        public virtual ICollection<Contacto_Puesto> Contacto_Puesto2 { get; set; }
        public virtual ICollection<Contactos> Contactos { get; set; }
        public virtual ICollection<Contactos> Contactos1 { get; set; }
        public virtual ICollection<Contactos> Contactos2 { get; set; }
        public virtual ICollection<Departamentos> Departamentos { get; set; }
        public virtual ICollection<Departamentos> Departamentos1 { get; set; }
        public virtual ICollection<Departamentos> Departamentos2 { get; set; }
        public virtual ICollection<Dias_Semana> Dias_Semana { get; set; }
        public virtual ICollection<Dias_Semana> Dias_Semana1 { get; set; }
        public virtual ICollection<Dias_Semana> Dias_Semana2 { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual ICollection<Empresa> Empresa1 { get; set; }
        public virtual ICollection<Empresa> Empresa2 { get; set; }
        public virtual ICollection<Empresa_Notorio> Empresa_Notorio { get; set; }
        public virtual ICollection<Empresa_Notorio> Empresa_Notorio1 { get; set; }
        public virtual ICollection<Empresa_Notorio> Empresa_Notorio2 { get; set; }
        public virtual ICollection<Estado_Civil> Estado_Civil { get; set; }
        public virtual ICollection<Estado_Civil> Estado_Civil1 { get; set; }
        public virtual ICollection<Estado_Civil> Estado_Civil2 { get; set; }
        public virtual ICollection<Genero> Genero { get; set; }
        public virtual ICollection<Genero> Genero1 { get; set; }
        public virtual ICollection<Genero> Genero2 { get; set; }
        public virtual ICollection<Monedas> Monedas { get; set; }
        public virtual ICollection<Monedas> Monedas1 { get; set; }
        public virtual ICollection<Monedas> Monedas2 { get; set; }
        public virtual ICollection<Municipios> Municipios { get; set; }
        public virtual ICollection<Municipios> Municipios1 { get; set; }
        public virtual ICollection<Municipios> Municipios2 { get; set; }
        public virtual ICollection<Notorio> Notorio { get; set; }
        public virtual ICollection<Notorio> Notorio1 { get; set; }
        public virtual ICollection<Notorio> Notorio2 { get; set; }
        public virtual ICollection<Paises> Paises { get; set; }
        public virtual ICollection<Paises> Paises1 { get; set; }
        public virtual ICollection<Paises> Paises2 { get; set; }
        public virtual ICollection<Profesion> Profesion { get; set; }
        public virtual ICollection<Profesion> Profesion1 { get; set; }
        public virtual ICollection<Profesion> Profesion2 { get; set; }
        public virtual ICollection<Razon_Social_Contacto> Razon_Social_Contacto { get; set; }
        public virtual ICollection<Razon_Social_Contacto> Razon_Social_Contacto1 { get; set; }
        public virtual ICollection<Razon_Social_Contacto> Razon_Social_Contacto2 { get; set; }
        public virtual ICollection<Razon_Social_Grupos_Factura> Razon_Social_Grupos_Factura { get; set; }
        public virtual ICollection<Razon_Social_Grupos_Factura> Razon_Social_Grupos_Factura1 { get; set; }
        public virtual ICollection<Razon_Social_Grupos_Factura> Razon_Social_Grupos_Factura2 { get; set; }
        public virtual ICollection<Razones_Sociales> Razones_Sociales { get; set; }
        public virtual ICollection<Razones_Sociales> Razones_Sociales1 { get; set; }
        public virtual ICollection<Razones_Sociales> Razones_Sociales2 { get; set; }
        public virtual ICollection<Representante> Representante { get; set; }
        public virtual ICollection<Representante> Representante1 { get; set; }
        public virtual ICollection<Representante> Representante2 { get; set; }
        public virtual ICollection<Representante_Empresa> Representante_Empresa { get; set; }
        public virtual ICollection<Representante_Empresa> Representante_Empresa1 { get; set; }
        public virtual ICollection<Representante_Empresa> Representante_Empresa2 { get; set; }
        public virtual ICollection<Tipo_Archivo> Tipo_Archivo { get; set; }
        public virtual ICollection<Tipo_Archivo> Tipo_Archivo1 { get; set; }
        public virtual ICollection<Tipo_Archivo> Tipo_Archivo2 { get; set; }
        public virtual ICollection<Tipo_Cliente> Tipo_Cliente { get; set; }
        public virtual ICollection<Tipo_Cliente> Tipo_Cliente1 { get; set; }
        public virtual ICollection<Tipo_Cliente> Tipo_Cliente2 { get; set; }
        public virtual ICollection<Tipo_Cuenta> Tipo_Cuenta { get; set; }
        public virtual ICollection<Tipo_Cuenta> Tipo_Cuenta1 { get; set; }
        public virtual ICollection<Tipo_Cuenta> Tipo_Cuenta2 { get; set; }
        public virtual ICollection<Tipo_Direccion> Tipo_Direccion { get; set; }
        public virtual ICollection<Tipo_Direccion> Tipo_Direccion1 { get; set; }
        public virtual ICollection<Tipo_Direccion> Tipo_Direccion2 { get; set; }
        public virtual ICollection<Tipo_Licencia> Tipo_Licencia { get; set; }
        public virtual ICollection<Tipo_Licencia> Tipo_Licencia1 { get; set; }
        public virtual ICollection<Tipo_Licencia> Tipo_Licencia2 { get; set; }
        public virtual ICollection<Tipo_Servicio> Tipo_Servicio { get; set; }
        public virtual ICollection<Tipo_Servicio> Tipo_Servicio1 { get; set; }
        public virtual ICollection<Tipo_Servicio> Tipo_Servicio2 { get; set; }
        public virtual ICollection<Tipo_Telefono> Tipo_Telefono { get; set; }
        public virtual ICollection<Tipo_Telefono> Tipo_Telefono1 { get; set; }
        public virtual ICollection<Tipo_Telefono> Tipo_Telefono2 { get; set; }
        public virtual ICollection<Ubicaciones> Ubicaciones { get; set; }
        public virtual ICollection<Ubicaciones> Ubicaciones1 { get; set; }
        public virtual ICollection<Ubicaciones> Ubicaciones2 { get; set; }
        public virtual ICollection<Cat_Estado_Proceso_Facturacion_Detalle> Cat_Estado_Proceso_Facturacion_Detalle { get; set; }
        public virtual ICollection<Cat_Estado_Proceso_Facturacion_Detalle> Cat_Estado_Proceso_Facturacion_Detalle1 { get; set; }
        public virtual ICollection<Cat_Estado_Proceso_Facturacion_Detalle> Cat_Estado_Proceso_Facturacion_Detalle2 { get; set; }
        public virtual ICollection<Cat_Razones_Anulacion> Cat_Razones_Anulacion { get; set; }
        public virtual ICollection<Cat_Razones_Anulacion> Cat_Razones_Anulacion1 { get; set; }
        public virtual ICollection<Cat_Razones_Anulacion> Cat_Razones_Anulacion2 { get; set; }
        public virtual ICollection<Cat_Razones_Eliminacion> Cat_Razones_Eliminacion { get; set; }
        public virtual ICollection<Cat_Razones_Eliminacion> Cat_Razones_Eliminacion1 { get; set; }
        public virtual ICollection<Cat_Razones_Eliminacion> Cat_Razones_Eliminacion2 { get; set; }
        public virtual ICollection<Contratos_Servicios> Contratos_Servicios { get; set; }
        public virtual ICollection<Contratos_Servicios> Contratos_Servicios1 { get; set; }
        public virtual ICollection<Contratos_Servicios> Contratos_Servicios2 { get; set; }
        public virtual ICollection<Cat_Estados_Factura> Cat_Estados_Factura { get; set; }
        public virtual ICollection<Cat_Estados_Factura> Cat_Estados_Factura1 { get; set; }
        public virtual ICollection<Cat_Estados_Factura> Cat_Estados_Factura2 { get; set; }
        public virtual ICollection<Cat_Estados_Servicio_Contratado> Cat_Estados_Servicio_Contratado { get; set; }
        public virtual ICollection<Cat_Estados_Servicio_Contratado> Cat_Estados_Servicio_Contratado1 { get; set; }
        public virtual ICollection<Cat_Estados_Servicio_Contratado> Cat_Estados_Servicio_Contratado2 { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual ICollection<Facturas> Facturas1 { get; set; }
        public virtual ICollection<Facturas> Facturas2 { get; set; }
        public virtual ICollection<Facturas_Detalle> Facturas_Detalle { get; set; }
        public virtual ICollection<Facturas_Detalle> Facturas_Detalle1 { get; set; }
        public virtual ICollection<Facturas_Detalle> Facturas_Detalle2 { get; set; }
        public virtual ICollection<Archivo_Empleado> Archivo_Empleado { get; set; }
        public virtual ICollection<Archivo_Empleado> Archivo_Empleado1 { get; set; }
        public virtual ICollection<Archivo_Empleado> Archivo_Empleado2 { get; set; }
        public virtual ICollection<Asistencias_Extras_Empleado> Asistencias_Extras_Empleado { get; set; }
        public virtual ICollection<Asistencias_Extras_Empleado> Asistencias_Extras_Empleado1 { get; set; }
        public virtual ICollection<Asistencias_Extras_Empleado> Asistencias_Extras_Empleado2 { get; set; }
        public virtual ICollection<Bonificacion> Bonificacion { get; set; }
        public virtual ICollection<Bonificacion> Bonificacion1 { get; set; }
        public virtual ICollection<Bonificacion> Bonificacion2 { get; set; }
        public virtual ICollection<Capacitacion_Impartida> Capacitacion_Impartida { get; set; }
        public virtual ICollection<Capacitacion_Impartida> Capacitacion_Impartida1 { get; set; }
        public virtual ICollection<Capacitacion_Impartida> Capacitacion_Impartida2 { get; set; }
        public virtual ICollection<Capacitacion_Impartida> Capacitacion_Impartida3 { get; set; }
        public virtual ICollection<Capacitacion_Impartida> Capacitacion_Impartida4 { get; set; }
        public virtual ICollection<Capacitacion_Impartida> Capacitacion_Impartida5 { get; set; }
        public virtual ICollection<Carga_Estado_Fuerza> Carga_Estado_Fuerza { get; set; }
        public virtual ICollection<Cat_Otros_Servicios> Cat_Otros_Servicios { get; set; }
        public virtual ICollection<Cat_Otros_Servicios> Cat_Otros_Servicios1 { get; set; }
        public virtual ICollection<Cat_Otros_Servicios> Cat_Otros_Servicios2 { get; set; }
        public virtual ICollection<Cat_Tipos_Gestion> Cat_Tipos_Gestion { get; set; }
        public virtual ICollection<Cat_Tipos_Gestion> Cat_Tipos_Gestion1 { get; set; }
        public virtual ICollection<Cat_Tipos_Gestion> Cat_Tipos_Gestion2 { get; set; }
        public virtual ICollection<Cat_Tipos_Respuesta_Gestion> Cat_Tipos_Respuesta_Gestion { get; set; }
        public virtual ICollection<Cat_Tipos_Respuesta_Gestion> Cat_Tipos_Respuesta_Gestion1 { get; set; }
        public virtual ICollection<Cat_Tipos_Respuesta_Gestion> Cat_Tipos_Respuesta_Gestion2 { get; set; }
        public virtual ICollection<Cat_Tipos_Respuesta_Gestion> Cat_Tipos_Respuesta_Gestion3 { get; set; }
        public virtual ICollection<Cat_Tipos_Respuesta_Gestion> Cat_Tipos_Respuesta_Gestion4 { get; set; }
        public virtual ICollection<Cat_Tipos_Respuesta_Gestion> Cat_Tipos_Respuesta_Gestion5 { get; set; }
        public virtual ICollection<Contratos_Otros_Servicios> Contratos_Otros_Servicios { get; set; }
        public virtual ICollection<Contratos_Otros_Servicios> Contratos_Otros_Servicios1 { get; set; }
        public virtual ICollection<Contratos_Otros_Servicios> Contratos_Otros_Servicios2 { get; set; }
        public virtual ICollection<Contratos_Agentes> Contratos_Agentes { get; set; }
        public virtual ICollection<Contratos_Agentes> Contratos_Agentes1 { get; set; }
        public virtual ICollection<Contratos_Agentes> Contratos_Agentes2 { get; set; }
        public virtual ICollection<Curso_Empleado> Curso_Empleado { get; set; }
        public virtual ICollection<Curso_Empleado> Curso_Empleado1 { get; set; }
        public virtual ICollection<Curso_Empleado> Curso_Empleado2 { get; set; }
        public virtual ICollection<Descuento> Descuento { get; set; }
        public virtual ICollection<Descuento> Descuento1 { get; set; }
        public virtual ICollection<Descuento> Descuento2 { get; set; }
        public virtual ICollection<Descuento_Periodico> Descuento_Periodico { get; set; }
        public virtual ICollection<Descuento_Periodico> Descuento_Periodico1 { get; set; }
        public virtual ICollection<Descuento_Periodico> Descuento_Periodico2 { get; set; }
        public virtual ICollection<Documentos> Documentos { get; set; }
        public virtual ICollection<Documentos> Documentos1 { get; set; }
        public virtual ICollection<Documentos> Documentos2 { get; set; }
        public virtual ICollection<Documento_Puesto> Documento_Puesto { get; set; }
        public virtual ICollection<Documento_Puesto> Documento_Puesto1 { get; set; }
        public virtual ICollection<Documento_Puesto> Documento_Puesto2 { get; set; }
        public virtual ICollection<Empleado_Encabezado_Planilla> Empleado_Encabezado_Planilla { get; set; }
        public virtual ICollection<Empleado_Encabezado_Planilla> Empleado_Encabezado_Planilla1 { get; set; }
        public virtual ICollection<Empleado_Encabezado_Planilla> Empleado_Encabezado_Planilla2 { get; set; }
        public virtual ICollection<Empleado_Encabezado_Planilla> Empleado_Encabezado_Planilla3 { get; set; }
        public virtual ICollection<Empleado_Encabezado_Planilla> Empleado_Encabezado_Planilla4 { get; set; }
        public virtual ICollection<Empleado_Encabezado_Planilla> Empleado_Encabezado_Planilla5 { get; set; }
        public virtual ICollection<Empleado_Permisos_Ausencias> Empleado_Permisos_Ausencias { get; set; }
        public virtual ICollection<Empleado_Permisos_Ausencias> Empleado_Permisos_Ausencias1 { get; set; }
        public virtual ICollection<Empleado_Permisos_Ausencias> Empleado_Permisos_Ausencias2 { get; set; }
        public virtual ICollection<Empleado_Experiencia_Laboral> Empleado_Experiencia_Laboral { get; set; }
        public virtual ICollection<Empleado_Experiencia_Laboral> Empleado_Experiencia_Laboral1 { get; set; }
        public virtual ICollection<Empleado_Experiencia_Laboral> Empleado_Experiencia_Laboral2 { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual ICollection<Empleado> Empleado1 { get; set; }
        public virtual ICollection<Empleado> Empleado2 { get; set; }
        public virtual ICollection<Encabezado_Planilla> Encabezado_Planilla { get; set; }
        public virtual ICollection<Encabezado_Planilla> Encabezado_Planilla1 { get; set; }
        public virtual ICollection<Encabezado_Planilla> Encabezado_Planilla2 { get; set; }
        public virtual ICollection<Encabezado_Planilla> Encabezado_Planilla3 { get; set; }
        public virtual ICollection<Encabezado_Planilla> Encabezado_Planilla4 { get; set; }
        public virtual ICollection<Estado_Empleado> Estado_Empleado { get; set; }
        public virtual ICollection<Estado_Empleado> Estado_Empleado1 { get; set; }
        public virtual ICollection<Estado_Empleado> Estado_Empleado2 { get; set; }
        public virtual ICollection<Estado_Fuerza> Estado_Fuerza { get; set; }
        public virtual ICollection<Estado_Fuerza> Estado_Fuerza1 { get; set; }
        public virtual ICollection<Estado_Fuerza> Estado_Fuerza2 { get; set; }
        public virtual ICollection<Estado_Fuerza> Estado_Fuerza3 { get; set; }
        public virtual ICollection<Estado_Fuerza_Detalle> Estado_Fuerza_Detalle { get; set; }
        public virtual ICollection<Estado_Fuerza_Detalle> Estado_Fuerza_Detalle1 { get; set; }
        public virtual ICollection<Estado_Fuerza_Detalle> Estado_Fuerza_Detalle2 { get; set; }
        public virtual ICollection<Gestion_Cobro> Gestion_Cobro { get; set; }
        public virtual ICollection<Gestion_Cobro> Gestion_Cobro1 { get; set; }
        public virtual ICollection<Gestion_Cobro> Gestion_Cobro2 { get; set; }
        public virtual ICollection<Gestion_Cobro_Detalle> Gestion_Cobro_Detalle { get; set; }
        public virtual ICollection<Gestion_Cobro_Detalle> Gestion_Cobro_Detalle1 { get; set; }
        public virtual ICollection<Gestion_Cobro_Detalle> Gestion_Cobro_Detalle2 { get; set; }
        public virtual ICollection<Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle> Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle { get; set; }
        public virtual ICollection<Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle> Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle1 { get; set; }
        public virtual ICollection<Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle> Gestion_Cobro_Detalle_Proceso_Facturacion_Detalle2 { get; set; }
        public virtual ICollection<Grado_Estudio> Grado_Estudio { get; set; }
        public virtual ICollection<Grado_Estudio> Grado_Estudio1 { get; set; }
        public virtual ICollection<Grado_Estudio> Grado_Estudio2 { get; set; }
        public virtual ICollection<Motivo_Baja> Motivo_Baja { get; set; }
        public virtual ICollection<Motivo_Baja> Motivo_Baja1 { get; set; }
        public virtual ICollection<Motivo_Baja> Motivo_Baja2 { get; set; }
        public virtual ICollection<Periodo> Periodo { get; set; }
        public virtual ICollection<Periodo> Periodo1 { get; set; }
        public virtual ICollection<Periodo> Periodo2 { get; set; }
        public virtual ICollection<Periodo> Periodo3 { get; set; }
        public virtual ICollection<Periodo> Periodo4 { get; set; }
        public virtual ICollection<Periodo> Periodo5 { get; set; }
        public virtual ICollection<Planilla> Planilla { get; set; }
        public virtual ICollection<Planilla> Planilla1 { get; set; }
        public virtual ICollection<Planilla> Planilla2 { get; set; }
        public virtual ICollection<Salario> Salario { get; set; }
        public virtual ICollection<Salario> Salario1 { get; set; }
        public virtual ICollection<Salario> Salario2 { get; set; }
        public virtual ICollection<Situacion> Situacion { get; set; }
        public virtual ICollection<Situacion> Situacion1 { get; set; }
        public virtual ICollection<Situacion> Situacion2 { get; set; }
        public virtual ICollection<Tipo_Bono> Tipo_Bono { get; set; }
        public virtual ICollection<Tipo_Bono> Tipo_Bono1 { get; set; }
        public virtual ICollection<Tipo_Bono> Tipo_Bono2 { get; set; }
        public virtual ICollection<Tipo_Descuento> Tipo_Descuento { get; set; }
        public virtual ICollection<Tipo_Descuento> Tipo_Descuento1 { get; set; }
        public virtual ICollection<Tipo_Descuento> Tipo_Descuento2 { get; set; }
        public virtual ICollection<Tipo_Pago> Tipo_Pago { get; set; }
        public virtual ICollection<Tipo_Pago> Tipo_Pago1 { get; set; }
        public virtual ICollection<Tipo_Pago> Tipo_Pago2 { get; set; }
        public virtual ICollection<Tipo_Permiso_Ausencia> Tipo_Permiso_Ausencia { get; set; }
        public virtual ICollection<Tipo_Permiso_Ausencia> Tipo_Permiso_Ausencia1 { get; set; }
        public virtual ICollection<Tipo_Permiso_Ausencia> Tipo_Permiso_Ausencia2 { get; set; }
        public virtual ICollection<Tipo_Permiso_Ausencia> Tipo_Permiso_Ausencia3 { get; set; }
        public virtual ICollection<Tipo_Permiso_Ausencia> Tipo_Permiso_Ausencia4 { get; set; }
        public virtual ICollection<Tipo_Permiso_Ausencia> Tipo_Permiso_Ausencia5 { get; set; }
        public virtual ICollection<Tipo_Planilla> Tipo_Planilla { get; set; }
        public virtual ICollection<Tipo_Planilla> Tipo_Planilla1 { get; set; }
        public virtual ICollection<Tipo_Planilla> Tipo_Planilla2 { get; set; }
        public virtual ICollection<Tipo_Plan_Pago> Tipo_Plan_Pago { get; set; }
        public virtual ICollection<Tipo_Plan_Pago> Tipo_Plan_Pago1 { get; set; }
        public virtual ICollection<Tipo_Plan_Pago> Tipo_Plan_Pago2 { get; set; }
        public virtual ICollection<Tipo_Prestamo> Tipo_Prestamo { get; set; }
        public virtual ICollection<Tipo_Prestamo> Tipo_Prestamo1 { get; set; }
        public virtual ICollection<Tipo_Prestamo> Tipo_Prestamo2 { get; set; }
        public virtual ICollection<Tipo_Puesto> Tipo_Puesto { get; set; }
        public virtual ICollection<Tipo_Puesto> Tipo_Puesto1 { get; set; }
        public virtual ICollection<Tipo_Puesto> Tipo_Puesto2 { get; set; }
        public virtual ICollection<Vacacion_Contrato> Vacacion_Contrato { get; set; }
        public virtual ICollection<Vacacion_Contrato> Vacacion_Contrato1 { get; set; }
        public virtual ICollection<Vacacion_Contrato> Vacacion_Contrato2 { get; set; }
        public virtual ICollection<Vacacion_Contrato> Vacacion_Contrato3 { get; set; }
        public virtual ICollection<Vacacion_Contrato> Vacacion_Contrato4 { get; set; }
        public virtual ICollection<Vacacion_Contrato> Vacacion_Contrato5 { get; set; }
        public virtual ICollection<Vacacion_Detalle> Vacacion_Detalle { get; set; }
        public virtual ICollection<Vacacion_Detalle> Vacacion_Detalle1 { get; set; }
        public virtual ICollection<Vacacion_Detalle> Vacacion_Detalle2 { get; set; }
        public virtual ICollection<Academia> Academia { get; set; }
        public virtual ICollection<Academia> Academia1 { get; set; }
        public virtual ICollection<Academia> Academia2 { get; set; }
        public virtual ICollection<Aprendiz> Aprendiz { get; set; }
        public virtual ICollection<Aprendiz> Aprendiz1 { get; set; }
        public virtual ICollection<Aprendiz> Aprendiz2 { get; set; }
        public virtual ICollection<Arma_Estado_Policia> Arma_Estado_Policia { get; set; }
        public virtual ICollection<Arma_Estado_Policia> Arma_Estado_Policia1 { get; set; }
        public virtual ICollection<Arma_Estado_Policia> Arma_Estado_Policia2 { get; set; }
        public virtual ICollection<Arma_Estado> Arma_Estado { get; set; }
        public virtual ICollection<Arma_Estado> Arma_Estado1 { get; set; }
        public virtual ICollection<Arma_Estado> Arma_Estado2 { get; set; }
        public virtual ICollection<Arma_Tipo> Arma_Tipo { get; set; }
        public virtual ICollection<Arma_Tipo> Arma_Tipo1 { get; set; }
        public virtual ICollection<Arma_Tipo> Arma_Tipo2 { get; set; }
        public virtual ICollection<Armas> Armas { get; set; }
        public virtual ICollection<Armas> Armas1 { get; set; }
        public virtual ICollection<Armas> Armas2 { get; set; }
        public virtual ICollection<Articulo_Tipo> Articulo_Tipo { get; set; }
        public virtual ICollection<Articulo_Tipo> Articulo_Tipo1 { get; set; }
        public virtual ICollection<Articulo_Tipo> Articulo_Tipo2 { get; set; }
        public virtual ICollection<Articulos> Articulos { get; set; }
        public virtual ICollection<Articulos> Articulos1 { get; set; }
        public virtual ICollection<Articulos> Articulos2 { get; set; }
        public virtual ICollection<Bodega_Inventario_Consumibles> Bodega_Inventario_Consumibles { get; set; }
        public virtual ICollection<Bodega_Inventario_Consumibles> Bodega_Inventario_Consumibles1 { get; set; }
        public virtual ICollection<Bodega_Inventario_Consumibles> Bodega_Inventario_Consumibles2 { get; set; }
        public virtual ICollection<Bodega_Inventario_Municiones> Bodega_Inventario_Municiones { get; set; }
        public virtual ICollection<Bodega_Inventario_Municiones> Bodega_Inventario_Municiones1 { get; set; }
        public virtual ICollection<Bodega_Inventario_Municiones> Bodega_Inventario_Municiones2 { get; set; }
        public virtual ICollection<Bodega_Inventario_Uniformes> Bodega_Inventario_Uniformes { get; set; }
        public virtual ICollection<Bodega_Inventario_Uniformes> Bodega_Inventario_Uniformes1 { get; set; }
        public virtual ICollection<Bodega_Inventario_Uniformes> Bodega_Inventario_Uniformes2 { get; set; }
        public virtual ICollection<Bodegas> Bodegas { get; set; }
        public virtual ICollection<Bodegas> Bodegas1 { get; set; }
        public virtual ICollection<Bodegas> Bodegas2 { get; set; }
        public virtual ICollection<Calibres> Calibres { get; set; }
        public virtual ICollection<Calibres> Calibres1 { get; set; }
        public virtual ICollection<Calibres> Calibres2 { get; set; }
        public virtual ICollection<Capacitacion_Curso> Capacitacion_Curso { get; set; }
        public virtual ICollection<Capacitacion_Curso> Capacitacion_Curso1 { get; set; }
        public virtual ICollection<Capacitacion_Curso> Capacitacion_Curso2 { get; set; }
        public virtual ICollection<Capacitacion> Capacitacion { get; set; }
        public virtual ICollection<Capacitacion> Capacitacion1 { get; set; }
        public virtual ICollection<Capacitacion> Capacitacion2 { get; set; }
        public virtual ICollection<Consumible_Tipo> Consumible_Tipo { get; set; }
        public virtual ICollection<Consumible_Tipo> Consumible_Tipo1 { get; set; }
        public virtual ICollection<Consumible_Tipo> Consumible_Tipo2 { get; set; }
        public virtual ICollection<Consumibles> Consumibles { get; set; }
        public virtual ICollection<Consumibles> Consumibles1 { get; set; }
        public virtual ICollection<Consumibles> Consumibles2 { get; set; }
        public virtual ICollection<Contratacion> Contratacion { get; set; }
        public virtual ICollection<Contratacion> Contratacion1 { get; set; }
        public virtual ICollection<Contratacion> Contratacion2 { get; set; }
        public virtual ICollection<Curso> Curso { get; set; }
        public virtual ICollection<Curso> Curso1 { get; set; }
        public virtual ICollection<Curso> Curso2 { get; set; }
        public virtual ICollection<Egreso_Estado> Egreso_Estado { get; set; }
        public virtual ICollection<Egreso_Estado> Egreso_Estado1 { get; set; }
        public virtual ICollection<Egreso_Estado> Egreso_Estado2 { get; set; }
        public virtual ICollection<Egreso_Tipo> Egreso_Tipo { get; set; }
        public virtual ICollection<Egreso_Tipo> Egreso_Tipo1 { get; set; }
        public virtual ICollection<Egreso_Tipo> Egreso_Tipo2 { get; set; }
        public virtual ICollection<Empleado_Direcciones> Empleado_Direcciones { get; set; }
        public virtual ICollection<Empleado_Direcciones> Empleado_Direcciones1 { get; set; }
        public virtual ICollection<Empleado_Direcciones> Empleado_Direcciones2 { get; set; }
        public virtual ICollection<Empleado_Telefono> Empleado_Telefono { get; set; }
        public virtual ICollection<Empleado_Telefono> Empleado_Telefono1 { get; set; }
        public virtual ICollection<Empleado_Telefono> Empleado_Telefono2 { get; set; }
        public virtual ICollection<Ingreso_Estado> Ingreso_Estado { get; set; }
        public virtual ICollection<Ingreso_Estado> Ingreso_Estado1 { get; set; }
        public virtual ICollection<Ingreso_Estado> Ingreso_Estado2 { get; set; }
        public virtual ICollection<Instructor> Instructor { get; set; }
        public virtual ICollection<Instructor> Instructor1 { get; set; }
        public virtual ICollection<Instructor> Instructor2 { get; set; }
        public virtual ICollection<Marca_Tipo> Marca_Tipo { get; set; }
        public virtual ICollection<Marca_Tipo> Marca_Tipo1 { get; set; }
        public virtual ICollection<Marca_Tipo> Marca_Tipo2 { get; set; }
        public virtual ICollection<Marcas> Marcas { get; set; }
        public virtual ICollection<Marcas> Marcas1 { get; set; }
        public virtual ICollection<Marcas> Marcas2 { get; set; }
        public virtual ICollection<Modelos> Modelos { get; set; }
        public virtual ICollection<Modelos> Modelos1 { get; set; }
        public virtual ICollection<Modelos> Modelos2 { get; set; }
        public virtual ICollection<Municiones> Municiones { get; set; }
        public virtual ICollection<Municiones> Municiones1 { get; set; }
        public virtual ICollection<Municiones> Municiones2 { get; set; }
        public virtual ICollection<Proveedores> Proveedores { get; set; }
        public virtual ICollection<Proveedores> Proveedores1 { get; set; }
        public virtual ICollection<Proveedores> Proveedores2 { get; set; }
        public virtual ICollection<Puesto> Puesto { get; set; }
        public virtual ICollection<Puesto> Puesto1 { get; set; }
        public virtual ICollection<Puesto> Puesto2 { get; set; }
        public virtual ICollection<Liquidaciones> Liquidaciones { get; set; }
        public virtual ICollection<Liquidaciones> Liquidaciones1 { get; set; }
        public virtual ICollection<Liquidaciones> Liquidaciones2 { get; set; }
        public virtual ICollection<Transaccion_Inventario_Tipo> Transaccion_Inventario_Tipo { get; set; }
        public virtual ICollection<Transaccion_Inventario_Tipo> Transaccion_Inventario_Tipo1 { get; set; }
        public virtual ICollection<Transaccion_Inventario_Tipo> Transaccion_Inventario_Tipo2 { get; set; }
        public virtual ICollection<Transaccion_Inventario_Detalle> Transaccion_Inventario_Detalle { get; set; }
        public virtual ICollection<Transaccion_Inventario_Detalle> Transaccion_Inventario_Detalle1 { get; set; }
        public virtual ICollection<Transaccion_Inventario_Detalle> Transaccion_Inventario_Detalle2 { get; set; }
        public virtual ICollection<Transacciones_Inventario> Transacciones_Inventario { get; set; }
        public virtual ICollection<Transacciones_Inventario> Transacciones_Inventario1 { get; set; }
        public virtual ICollection<Transacciones_Inventario> Transacciones_Inventario2 { get; set; }
        public virtual ICollection<Traslado_Estado> Traslado_Estado { get; set; }
        public virtual ICollection<Traslado_Estado> Traslado_Estado1 { get; set; }
        public virtual ICollection<Traslado_Estado> Traslado_Estado2 { get; set; }
        public virtual ICollection<Uniforme_Tipo> Uniforme_Tipo { get; set; }
        public virtual ICollection<Uniforme_Tipo> Uniforme_Tipo1 { get; set; }
        public virtual ICollection<Uniforme_Tipo> Uniforme_Tipo2 { get; set; }
        public virtual ICollection<Uniformes> Uniformes { get; set; }
        public virtual ICollection<Uniformes> Uniformes1 { get; set; }
        public virtual ICollection<Uniformes> Uniformes2 { get; set; }
        public virtual ICollection<Procesos_Facturacion> Procesos_Facturacion { get; set; }
        public virtual ICollection<Procesos_Facturacion> Procesos_Facturacion1 { get; set; }
        public virtual ICollection<Procesos_Facturacion> Procesos_Facturacion2 { get; set; }
        public virtual ICollection<Procesos_Facturacion_Detalle> Procesos_Facturacion_Detalle { get; set; }
        public virtual ICollection<Procesos_Facturacion_Detalle> Procesos_Facturacion_Detalle1 { get; set; }
        public virtual ICollection<Procesos_Facturacion_Detalle> Procesos_Facturacion_Detalle2 { get; set; }
        public virtual ICollection<Series_Facturas> Series_Facturas { get; set; }
        public virtual ICollection<Series_Facturas> Series_Facturas1 { get; set; }
        public virtual ICollection<Series_Facturas> Series_Facturas2 { get; set; }
        public virtual ICollection<Cat_Tipos_Agente> Cat_Tipos_Agente { get; set; }
        public virtual ICollection<Cat_Tipos_Agente> Cat_Tipos_Agente1 { get; set; }
        public virtual ICollection<Cat_Tipos_Agente> Cat_Tipos_Agente2 { get; set; }
        public virtual ICollection<Cat_Tipos_Facturacion> Cat_Tipos_Facturacion { get; set; }
        public virtual ICollection<Cat_Tipos_Facturacion> Cat_Tipos_Facturacion1 { get; set; }
        public virtual ICollection<Cat_Tipos_Facturacion> Cat_Tipos_Facturacion2 { get; set; }
        public virtual ICollection<Tickets_Generacion> Tickets_Generacion { get; set; }
        public virtual ICollection<Tickets_Generacion> Tickets_Generacion1 { get; set; }
        public virtual ICollection<Tickets_Generacion> Tickets_Generacion2 { get; set; }
        public virtual ICollection<Tickets_Inventario> Tickets_Inventario { get; set; }
        public virtual ICollection<Tickets_Inventario> Tickets_Inventario1 { get; set; }
        public virtual ICollection<Tickets_Inventario> Tickets_Inventario2 { get; set; }
        public virtual ICollection<Tickets_Inventario> Tickets_Inventario3 { get; set; }
        public virtual ICollection<Tickets_Movimiento> Tickets_Movimiento { get; set; }
        public virtual ICollection<Tickets_Movimiento> Tickets_Movimiento1 { get; set; }
        public virtual ICollection<Tickets_Movimiento> Tickets_Movimiento2 { get; set; }
        public virtual ICollection<Tickets_Movimiento> Tickets_Movimiento3 { get; set; }
        public virtual ICollection<Tickets_Tipo> Tickets_Tipo { get; set; }
        public virtual ICollection<Tickets_Tipo> Tickets_Tipo1 { get; set; }
        public virtual ICollection<Tickets_Tipo> Tickets_Tipo2 { get; set; }
        public virtual ICollection<Tickets_Tipo_Movimiento> Tickets_Tipo_Movimiento { get; set; }
        public virtual ICollection<Tickets_Tipo_Movimiento> Tickets_Tipo_Movimiento1 { get; set; }
        public virtual ICollection<Tickets_Tipo_Movimiento> Tickets_Tipo_Movimiento2 { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
        public virtual ICollection<Egreso_Detalle> Egreso_Detalle { get; set; }
        public virtual ICollection<Egreso_Detalle> Egreso_Detalle1 { get; set; }
        public virtual ICollection<Egreso_Detalle> Egreso_Detalle2 { get; set; }
        public virtual ICollection<Egresos> Egresos { get; set; }
        public virtual ICollection<Egresos> Egresos1 { get; set; }
        public virtual ICollection<Egresos> Egresos2 { get; set; }
        public virtual ICollection<Egresos> Egresos3 { get; set; }
        public virtual ICollection<Ingreso_Detalle> Ingreso_Detalle { get; set; }
        public virtual ICollection<Ingreso_Detalle> Ingreso_Detalle1 { get; set; }
        public virtual ICollection<Ingreso_Detalle> Ingreso_Detalle2 { get; set; }
        public virtual ICollection<Ingresos> Ingresos { get; set; }
        public virtual ICollection<Ingresos> Ingresos1 { get; set; }
        public virtual ICollection<Ingresos> Ingresos2 { get; set; }
        public virtual ICollection<Ingresos> Ingresos3 { get; set; }
        public virtual ICollection<Traslado_Detalle> Traslado_Detalle { get; set; }
        public virtual ICollection<Traslado_Detalle> Traslado_Detalle1 { get; set; }
        public virtual ICollection<Traslado_Detalle> Traslado_Detalle2 { get; set; }
        public virtual ICollection<Traslados> Traslados { get; set; }
        public virtual ICollection<Traslados> Traslados1 { get; set; }
        public virtual ICollection<Traslados> Traslados2 { get; set; }
        public virtual ICollection<Traslados> Traslados3 { get; set; }
    }
}
